// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dcrwalletgui.proto

package dcrwalletgui

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Network int32

const (
	Network_MAINNET Network = 0
	Network_TESTNET Network = 1
	Network_SIMNET  Network = 2
)

var Network_name = map[int32]string{
	0: "MAINNET",
	1: "TESTNET",
	2: "SIMNET",
}

var Network_value = map[string]int32{
	"MAINNET": 0,
	"TESTNET": 1,
	"SIMNET":  2,
}

func (x Network) String() string {
	return proto.EnumName(Network_name, int32(x))
}

func (Network) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{0}
}

type SetConfigResponse_UpdateStatus int32

const (
	SetConfigResponse_STATUS_SUCCESS SetConfigResponse_UpdateStatus = 0
	SetConfigResponse_STATUS_ERROR   SetConfigResponse_UpdateStatus = 1
)

var SetConfigResponse_UpdateStatus_name = map[int32]string{
	0: "STATUS_SUCCESS",
	1: "STATUS_ERROR",
}

var SetConfigResponse_UpdateStatus_value = map[string]int32{
	"STATUS_SUCCESS": 0,
	"STATUS_ERROR":   1,
}

func (x SetConfigResponse_UpdateStatus) String() string {
	return proto.EnumName(SetConfigResponse_UpdateStatus_name, int32(x))
}

func (SetConfigResponse_UpdateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{2, 0}
}

type GetConfigRequest struct {
	Passphrase           []byte   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{0}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

type SetConfigRequest struct {
	AppConfig            *AppConfiguration `protobuf:"bytes,1,opt,name=app_config,json=appConfig,proto3" json:"app_config,omitempty"`
	Passphrase           []byte            `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{1}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetAppConfig() *AppConfiguration {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

func (m *SetConfigRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

type SetConfigResponse struct {
	UpdateStatus         SetConfigResponse_UpdateStatus `protobuf:"varint,1,opt,name=update_status,json=updateStatus,proto3,enum=dcrwalletgui.SetConfigResponse_UpdateStatus" json:"update_status,omitempty"`
	ErrorCode            int32                          `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorDescription     string                         `protobuf:"bytes,3,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SetConfigResponse) Reset()         { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()    {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{2}
}

func (m *SetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigResponse.Unmarshal(m, b)
}
func (m *SetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigResponse.Merge(m, src)
}
func (m *SetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigResponse.Size(m)
}
func (m *SetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigResponse proto.InternalMessageInfo

func (m *SetConfigResponse) GetUpdateStatus() SetConfigResponse_UpdateStatus {
	if m != nil {
		return m.UpdateStatus
	}
	return SetConfigResponse_STATUS_SUCCESS
}

func (m *SetConfigResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *SetConfigResponse) GetErrorDescription() string {
	if m != nil {
		return m.ErrorDescription
	}
	return ""
}

type RPCEndpoint struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	CertFileName         string   `protobuf:"bytes,6,opt,name=cert_file_name,json=certFileName,proto3" json:"cert_file_name,omitempty"`
	CertBlob             string   `protobuf:"bytes,7,opt,name=cert_blob,json=certBlob,proto3" json:"cert_blob,omitempty"`
	Network              Network  `protobuf:"varint,8,opt,name=network,proto3,enum=dcrwalletgui.Network" json:"network,omitempty"`
	Label                string   `protobuf:"bytes,9,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCEndpoint) Reset()         { *m = RPCEndpoint{} }
func (m *RPCEndpoint) String() string { return proto.CompactTextString(m) }
func (*RPCEndpoint) ProtoMessage()    {}
func (*RPCEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{3}
}

func (m *RPCEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCEndpoint.Unmarshal(m, b)
}
func (m *RPCEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCEndpoint.Marshal(b, m, deterministic)
}
func (m *RPCEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCEndpoint.Merge(m, src)
}
func (m *RPCEndpoint) XXX_Size() int {
	return xxx_messageInfo_RPCEndpoint.Size(m)
}
func (m *RPCEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_RPCEndpoint proto.InternalMessageInfo

func (m *RPCEndpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RPCEndpoint) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RPCEndpoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RPCEndpoint) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RPCEndpoint) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RPCEndpoint) GetCertFileName() string {
	if m != nil {
		return m.CertFileName
	}
	return ""
}

func (m *RPCEndpoint) GetCertBlob() string {
	if m != nil {
		return m.CertBlob
	}
	return ""
}

func (m *RPCEndpoint) GetNetwork() Network {
	if m != nil {
		return m.Network
	}
	return Network_MAINNET
}

func (m *RPCEndpoint) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type GRPCEndpoint struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	CertFileName         string   `protobuf:"bytes,4,opt,name=cert_file_name,json=certFileName,proto3" json:"cert_file_name,omitempty"`
	CertBlob             string   `protobuf:"bytes,5,opt,name=cert_blob,json=certBlob,proto3" json:"cert_blob,omitempty"`
	Network              Network  `protobuf:"varint,6,opt,name=network,proto3,enum=dcrwalletgui.Network" json:"network,omitempty"`
	Label                string   `protobuf:"bytes,7,opt,name=label,proto3" json:"label,omitempty"`
	IsWatchingOnly       bool     `protobuf:"varint,8,opt,name=is_watching_only,json=isWatchingOnly,proto3" json:"is_watching_only,omitempty"`
	ActiveNetwork        uint32   `protobuf:"varint,9,opt,name=active_network,json=activeNetwork,proto3" json:"active_network,omitempty"`
	CoinType             uint32   `protobuf:"varint,10,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GRPCEndpoint) Reset()         { *m = GRPCEndpoint{} }
func (m *GRPCEndpoint) String() string { return proto.CompactTextString(m) }
func (*GRPCEndpoint) ProtoMessage()    {}
func (*GRPCEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{4}
}

func (m *GRPCEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GRPCEndpoint.Unmarshal(m, b)
}
func (m *GRPCEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GRPCEndpoint.Marshal(b, m, deterministic)
}
func (m *GRPCEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GRPCEndpoint.Merge(m, src)
}
func (m *GRPCEndpoint) XXX_Size() int {
	return xxx_messageInfo_GRPCEndpoint.Size(m)
}
func (m *GRPCEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_GRPCEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_GRPCEndpoint proto.InternalMessageInfo

func (m *GRPCEndpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GRPCEndpoint) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *GRPCEndpoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GRPCEndpoint) GetCertFileName() string {
	if m != nil {
		return m.CertFileName
	}
	return ""
}

func (m *GRPCEndpoint) GetCertBlob() string {
	if m != nil {
		return m.CertBlob
	}
	return ""
}

func (m *GRPCEndpoint) GetNetwork() Network {
	if m != nil {
		return m.Network
	}
	return Network_MAINNET
}

func (m *GRPCEndpoint) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *GRPCEndpoint) GetIsWatchingOnly() bool {
	if m != nil {
		return m.IsWatchingOnly
	}
	return false
}

func (m *GRPCEndpoint) GetActiveNetwork() uint32 {
	if m != nil {
		return m.ActiveNetwork
	}
	return 0
}

func (m *GRPCEndpoint) GetCoinType() uint32 {
	if m != nil {
		return m.CoinType
	}
	return 0
}

type AccountPreference struct {
	AccountNumber        uint32   `protobuf:"varint,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	IsHidden             bool     `protobuf:"varint,2,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	DisplayOrder         uint32   `protobuf:"varint,3,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountPreference) Reset()         { *m = AccountPreference{} }
func (m *AccountPreference) String() string { return proto.CompactTextString(m) }
func (*AccountPreference) ProtoMessage()    {}
func (*AccountPreference) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{5}
}

func (m *AccountPreference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPreference.Unmarshal(m, b)
}
func (m *AccountPreference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPreference.Marshal(b, m, deterministic)
}
func (m *AccountPreference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPreference.Merge(m, src)
}
func (m *AccountPreference) XXX_Size() int {
	return xxx_messageInfo_AccountPreference.Size(m)
}
func (m *AccountPreference) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPreference.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPreference proto.InternalMessageInfo

func (m *AccountPreference) GetAccountNumber() uint32 {
	if m != nil {
		return m.AccountNumber
	}
	return 0
}

func (m *AccountPreference) GetIsHidden() bool {
	if m != nil {
		return m.IsHidden
	}
	return false
}

func (m *AccountPreference) GetDisplayOrder() uint32 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

type WalletPreferences struct {
	WalletEndpointId     string               `protobuf:"bytes,1,opt,name=wallet_endpoint_id,json=walletEndpointId,proto3" json:"wallet_endpoint_id,omitempty"`
	AccountPrefs         []*AccountPreference `protobuf:"bytes,2,rep,name=account_prefs,json=accountPrefs,proto3" json:"account_prefs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WalletPreferences) Reset()         { *m = WalletPreferences{} }
func (m *WalletPreferences) String() string { return proto.CompactTextString(m) }
func (*WalletPreferences) ProtoMessage()    {}
func (*WalletPreferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{6}
}

func (m *WalletPreferences) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletPreferences.Unmarshal(m, b)
}
func (m *WalletPreferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletPreferences.Marshal(b, m, deterministic)
}
func (m *WalletPreferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletPreferences.Merge(m, src)
}
func (m *WalletPreferences) XXX_Size() int {
	return xxx_messageInfo_WalletPreferences.Size(m)
}
func (m *WalletPreferences) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletPreferences.DiscardUnknown(m)
}

var xxx_messageInfo_WalletPreferences proto.InternalMessageInfo

func (m *WalletPreferences) GetWalletEndpointId() string {
	if m != nil {
		return m.WalletEndpointId
	}
	return ""
}

func (m *WalletPreferences) GetAccountPrefs() []*AccountPreference {
	if m != nil {
		return m.AccountPrefs
	}
	return nil
}

type RunTicketBuyerRequest struct {
	Passphrase           []byte   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	Account              uint32   `protobuf:"varint,2,opt,name=account,proto3" json:"account,omitempty"`
	VotingAccount        uint32   `protobuf:"varint,3,opt,name=voting_account,json=votingAccount,proto3" json:"voting_account,omitempty"`
	BalanceToMaintain    int64    `protobuf:"varint,4,opt,name=balance_to_maintain,json=balanceToMaintain,proto3" json:"balance_to_maintain,omitempty"`
	VotingAddress        string   `protobuf:"bytes,5,opt,name=voting_address,json=votingAddress,proto3" json:"voting_address,omitempty"`
	PoolAddress          string   `protobuf:"bytes,6,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	PoolFees             float64  `protobuf:"fixed64,7,opt,name=pool_fees,json=poolFees,proto3" json:"pool_fees,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunTicketBuyerRequest) Reset()         { *m = RunTicketBuyerRequest{} }
func (m *RunTicketBuyerRequest) String() string { return proto.CompactTextString(m) }
func (*RunTicketBuyerRequest) ProtoMessage()    {}
func (*RunTicketBuyerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{7}
}

func (m *RunTicketBuyerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTicketBuyerRequest.Unmarshal(m, b)
}
func (m *RunTicketBuyerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTicketBuyerRequest.Marshal(b, m, deterministic)
}
func (m *RunTicketBuyerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTicketBuyerRequest.Merge(m, src)
}
func (m *RunTicketBuyerRequest) XXX_Size() int {
	return xxx_messageInfo_RunTicketBuyerRequest.Size(m)
}
func (m *RunTicketBuyerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTicketBuyerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunTicketBuyerRequest proto.InternalMessageInfo

func (m *RunTicketBuyerRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

func (m *RunTicketBuyerRequest) GetAccount() uint32 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *RunTicketBuyerRequest) GetVotingAccount() uint32 {
	if m != nil {
		return m.VotingAccount
	}
	return 0
}

func (m *RunTicketBuyerRequest) GetBalanceToMaintain() int64 {
	if m != nil {
		return m.BalanceToMaintain
	}
	return 0
}

func (m *RunTicketBuyerRequest) GetVotingAddress() string {
	if m != nil {
		return m.VotingAddress
	}
	return ""
}

func (m *RunTicketBuyerRequest) GetPoolAddress() string {
	if m != nil {
		return m.PoolAddress
	}
	return ""
}

func (m *RunTicketBuyerRequest) GetPoolFees() float64 {
	if m != nil {
		return m.PoolFees
	}
	return 0
}

type RunAccountMixerRequest struct {
	Passphrase           []byte   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	MixedAccount         uint32   `protobuf:"varint,2,opt,name=mixed_account,json=mixedAccount,proto3" json:"mixed_account,omitempty"`
	MixedAccountBranch   uint32   `protobuf:"varint,3,opt,name=mixed_account_branch,json=mixedAccountBranch,proto3" json:"mixed_account_branch,omitempty"`
	ChangeAccount        uint32   `protobuf:"varint,4,opt,name=change_account,json=changeAccount,proto3" json:"change_account,omitempty"`
	CsppServer           string   `protobuf:"bytes,5,opt,name=cspp_server,json=csppServer,proto3" json:"cspp_server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunAccountMixerRequest) Reset()         { *m = RunAccountMixerRequest{} }
func (m *RunAccountMixerRequest) String() string { return proto.CompactTextString(m) }
func (*RunAccountMixerRequest) ProtoMessage()    {}
func (*RunAccountMixerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{8}
}

func (m *RunAccountMixerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunAccountMixerRequest.Unmarshal(m, b)
}
func (m *RunAccountMixerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunAccountMixerRequest.Marshal(b, m, deterministic)
}
func (m *RunAccountMixerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunAccountMixerRequest.Merge(m, src)
}
func (m *RunAccountMixerRequest) XXX_Size() int {
	return xxx_messageInfo_RunAccountMixerRequest.Size(m)
}
func (m *RunAccountMixerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunAccountMixerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunAccountMixerRequest proto.InternalMessageInfo

func (m *RunAccountMixerRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

func (m *RunAccountMixerRequest) GetMixedAccount() uint32 {
	if m != nil {
		return m.MixedAccount
	}
	return 0
}

func (m *RunAccountMixerRequest) GetMixedAccountBranch() uint32 {
	if m != nil {
		return m.MixedAccountBranch
	}
	return 0
}

func (m *RunAccountMixerRequest) GetChangeAccount() uint32 {
	if m != nil {
		return m.ChangeAccount
	}
	return 0
}

func (m *RunAccountMixerRequest) GetCsppServer() string {
	if m != nil {
		return m.CsppServer
	}
	return ""
}

type AppConfiguration struct {
	DcrdEndpoint                *RPCEndpoint            `protobuf:"bytes,1,opt,name=dcrd_endpoint,json=dcrdEndpoint,proto3" json:"dcrd_endpoint,omitempty"`
	WalletEndpoints             []*GRPCEndpoint         `protobuf:"bytes,2,rep,name=wallet_endpoints,json=walletEndpoints,proto3" json:"wallet_endpoints,omitempty"`
	DefaultWalletEndpointId     string                  `protobuf:"bytes,3,opt,name=default_wallet_endpoint_id,json=defaultWalletEndpointId,proto3" json:"default_wallet_endpoint_id,omitempty"`
	WalletPreferences           []*WalletPreferences    `protobuf:"bytes,4,rep,name=wallet_preferences,json=walletPreferences,proto3" json:"wallet_preferences,omitempty"`
	AccountMixerRequestDefaults *RunAccountMixerRequest `protobuf:"bytes,5,opt,name=account_mixer_request_defaults,json=accountMixerRequestDefaults,proto3" json:"account_mixer_request_defaults,omitempty"`
	RunAutoBuyerRequestDefaults *RunTicketBuyerRequest  `protobuf:"bytes,6,opt,name=run_auto_buyer_request_defaults,json=runAutoBuyerRequestDefaults,proto3" json:"run_auto_buyer_request_defaults,omitempty"`
	AltDisplayCurrencies        []string                `protobuf:"bytes,7,rep,name=alt_display_currencies,json=altDisplayCurrencies,proto3" json:"alt_display_currencies,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                `json:"-"`
	XXX_unrecognized            []byte                  `json:"-"`
	XXX_sizecache               int32                   `json:"-"`
}

func (m *AppConfiguration) Reset()         { *m = AppConfiguration{} }
func (m *AppConfiguration) String() string { return proto.CompactTextString(m) }
func (*AppConfiguration) ProtoMessage()    {}
func (*AppConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{9}
}

func (m *AppConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfiguration.Unmarshal(m, b)
}
func (m *AppConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfiguration.Marshal(b, m, deterministic)
}
func (m *AppConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfiguration.Merge(m, src)
}
func (m *AppConfiguration) XXX_Size() int {
	return xxx_messageInfo_AppConfiguration.Size(m)
}
func (m *AppConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfiguration proto.InternalMessageInfo

func (m *AppConfiguration) GetDcrdEndpoint() *RPCEndpoint {
	if m != nil {
		return m.DcrdEndpoint
	}
	return nil
}

func (m *AppConfiguration) GetWalletEndpoints() []*GRPCEndpoint {
	if m != nil {
		return m.WalletEndpoints
	}
	return nil
}

func (m *AppConfiguration) GetDefaultWalletEndpointId() string {
	if m != nil {
		return m.DefaultWalletEndpointId
	}
	return ""
}

func (m *AppConfiguration) GetWalletPreferences() []*WalletPreferences {
	if m != nil {
		return m.WalletPreferences
	}
	return nil
}

func (m *AppConfiguration) GetAccountMixerRequestDefaults() *RunAccountMixerRequest {
	if m != nil {
		return m.AccountMixerRequestDefaults
	}
	return nil
}

func (m *AppConfiguration) GetRunAutoBuyerRequestDefaults() *RunTicketBuyerRequest {
	if m != nil {
		return m.RunAutoBuyerRequestDefaults
	}
	return nil
}

func (m *AppConfiguration) GetAltDisplayCurrencies() []string {
	if m != nil {
		return m.AltDisplayCurrencies
	}
	return nil
}

type CheckConnectionRequest struct {
	GrpcEndpoint         *GRPCEndpoint `protobuf:"bytes,1,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	RpcEndpoint          *RPCEndpoint  `protobuf:"bytes,2,opt,name=rpc_endpoint,json=rpcEndpoint,proto3" json:"rpc_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CheckConnectionRequest) Reset()         { *m = CheckConnectionRequest{} }
func (m *CheckConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*CheckConnectionRequest) ProtoMessage()    {}
func (*CheckConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{10}
}

func (m *CheckConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckConnectionRequest.Unmarshal(m, b)
}
func (m *CheckConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckConnectionRequest.Marshal(b, m, deterministic)
}
func (m *CheckConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckConnectionRequest.Merge(m, src)
}
func (m *CheckConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_CheckConnectionRequest.Size(m)
}
func (m *CheckConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckConnectionRequest proto.InternalMessageInfo

func (m *CheckConnectionRequest) GetGrpcEndpoint() *GRPCEndpoint {
	if m != nil {
		return m.GrpcEndpoint
	}
	return nil
}

func (m *CheckConnectionRequest) GetRpcEndpoint() *RPCEndpoint {
	if m != nil {
		return m.RpcEndpoint
	}
	return nil
}

type CheckConnectionResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckConnectionResponse) Reset()         { *m = CheckConnectionResponse{} }
func (m *CheckConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*CheckConnectionResponse) ProtoMessage()    {}
func (*CheckConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{11}
}

func (m *CheckConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckConnectionResponse.Unmarshal(m, b)
}
func (m *CheckConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckConnectionResponse.Marshal(b, m, deterministic)
}
func (m *CheckConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckConnectionResponse.Merge(m, src)
}
func (m *CheckConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_CheckConnectionResponse.Size(m)
}
func (m *CheckConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckConnectionResponse proto.InternalMessageInfo

func (m *CheckConnectionResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *CheckConnectionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ConnectWalletRequest struct {
	WalletEndpointId     string   `protobuf:"bytes,1,opt,name=wallet_endpoint_id,json=walletEndpointId,proto3" json:"wallet_endpoint_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectWalletRequest) Reset()         { *m = ConnectWalletRequest{} }
func (m *ConnectWalletRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectWalletRequest) ProtoMessage()    {}
func (*ConnectWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{12}
}

func (m *ConnectWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectWalletRequest.Unmarshal(m, b)
}
func (m *ConnectWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectWalletRequest.Marshal(b, m, deterministic)
}
func (m *ConnectWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectWalletRequest.Merge(m, src)
}
func (m *ConnectWalletRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectWalletRequest.Size(m)
}
func (m *ConnectWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectWalletRequest proto.InternalMessageInfo

func (m *ConnectWalletRequest) GetWalletEndpointId() string {
	if m != nil {
		return m.WalletEndpointId
	}
	return ""
}

type ConnectWalletResponse struct {
	IsSuccess            bool          `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	Error                string        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Endpoint             *GRPCEndpoint `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConnectWalletResponse) Reset()         { *m = ConnectWalletResponse{} }
func (m *ConnectWalletResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectWalletResponse) ProtoMessage()    {}
func (*ConnectWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{13}
}

func (m *ConnectWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectWalletResponse.Unmarshal(m, b)
}
func (m *ConnectWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectWalletResponse.Marshal(b, m, deterministic)
}
func (m *ConnectWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectWalletResponse.Merge(m, src)
}
func (m *ConnectWalletResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectWalletResponse.Size(m)
}
func (m *ConnectWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectWalletResponse proto.InternalMessageInfo

func (m *ConnectWalletResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *ConnectWalletResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ConnectWalletResponse) GetEndpoint() *GRPCEndpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

// exchange rates
type AltCurrencyRates struct {
	Rates                []*AltCurrencyRates_AltCurrencyRate `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	LastUpdatedTs        int64                               `protobuf:"varint,2,opt,name=last_updated_ts,json=lastUpdatedTs,proto3" json:"last_updated_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *AltCurrencyRates) Reset()         { *m = AltCurrencyRates{} }
func (m *AltCurrencyRates) String() string { return proto.CompactTextString(m) }
func (*AltCurrencyRates) ProtoMessage()    {}
func (*AltCurrencyRates) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{14}
}

func (m *AltCurrencyRates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AltCurrencyRates.Unmarshal(m, b)
}
func (m *AltCurrencyRates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AltCurrencyRates.Marshal(b, m, deterministic)
}
func (m *AltCurrencyRates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AltCurrencyRates.Merge(m, src)
}
func (m *AltCurrencyRates) XXX_Size() int {
	return xxx_messageInfo_AltCurrencyRates.Size(m)
}
func (m *AltCurrencyRates) XXX_DiscardUnknown() {
	xxx_messageInfo_AltCurrencyRates.DiscardUnknown(m)
}

var xxx_messageInfo_AltCurrencyRates proto.InternalMessageInfo

func (m *AltCurrencyRates) GetRates() []*AltCurrencyRates_AltCurrencyRate {
	if m != nil {
		return m.Rates
	}
	return nil
}

func (m *AltCurrencyRates) GetLastUpdatedTs() int64 {
	if m != nil {
		return m.LastUpdatedTs
	}
	return 0
}

type AltCurrencyRates_AltCurrencyRate struct {
	CurrencyCode         string   `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CurrentRate          float32  `protobuf:"fixed32,2,opt,name=current_rate,json=currentRate,proto3" json:"current_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AltCurrencyRates_AltCurrencyRate) Reset()         { *m = AltCurrencyRates_AltCurrencyRate{} }
func (m *AltCurrencyRates_AltCurrencyRate) String() string { return proto.CompactTextString(m) }
func (*AltCurrencyRates_AltCurrencyRate) ProtoMessage()    {}
func (*AltCurrencyRates_AltCurrencyRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{14, 0}
}

func (m *AltCurrencyRates_AltCurrencyRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AltCurrencyRates_AltCurrencyRate.Unmarshal(m, b)
}
func (m *AltCurrencyRates_AltCurrencyRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AltCurrencyRates_AltCurrencyRate.Marshal(b, m, deterministic)
}
func (m *AltCurrencyRates_AltCurrencyRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AltCurrencyRates_AltCurrencyRate.Merge(m, src)
}
func (m *AltCurrencyRates_AltCurrencyRate) XXX_Size() int {
	return xxx_messageInfo_AltCurrencyRates_AltCurrencyRate.Size(m)
}
func (m *AltCurrencyRates_AltCurrencyRate) XXX_DiscardUnknown() {
	xxx_messageInfo_AltCurrencyRates_AltCurrencyRate.DiscardUnknown(m)
}

var xxx_messageInfo_AltCurrencyRates_AltCurrencyRate proto.InternalMessageInfo

func (m *AltCurrencyRates_AltCurrencyRate) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *AltCurrencyRates_AltCurrencyRate) GetCurrentRate() float32 {
	if m != nil {
		return m.CurrentRate
	}
	return 0
}

type GetMarketChartRequest struct {
	CurrencyCode         string   `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Days                 uint32   `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMarketChartRequest) Reset()         { *m = GetMarketChartRequest{} }
func (m *GetMarketChartRequest) String() string { return proto.CompactTextString(m) }
func (*GetMarketChartRequest) ProtoMessage()    {}
func (*GetMarketChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{15}
}

func (m *GetMarketChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketChartRequest.Unmarshal(m, b)
}
func (m *GetMarketChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketChartRequest.Marshal(b, m, deterministic)
}
func (m *GetMarketChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketChartRequest.Merge(m, src)
}
func (m *GetMarketChartRequest) XXX_Size() int {
	return xxx_messageInfo_GetMarketChartRequest.Size(m)
}
func (m *GetMarketChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketChartRequest proto.InternalMessageInfo

func (m *GetMarketChartRequest) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *GetMarketChartRequest) GetDays() uint32 {
	if m != nil {
		return m.Days
	}
	return 0
}

type MarketChartDataPoint struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExchangeRate         float32  `protobuf:"fixed32,2,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketChartDataPoint) Reset()         { *m = MarketChartDataPoint{} }
func (m *MarketChartDataPoint) String() string { return proto.CompactTextString(m) }
func (*MarketChartDataPoint) ProtoMessage()    {}
func (*MarketChartDataPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{16}
}

func (m *MarketChartDataPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketChartDataPoint.Unmarshal(m, b)
}
func (m *MarketChartDataPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketChartDataPoint.Marshal(b, m, deterministic)
}
func (m *MarketChartDataPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketChartDataPoint.Merge(m, src)
}
func (m *MarketChartDataPoint) XXX_Size() int {
	return xxx_messageInfo_MarketChartDataPoint.Size(m)
}
func (m *MarketChartDataPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketChartDataPoint.DiscardUnknown(m)
}

var xxx_messageInfo_MarketChartDataPoint proto.InternalMessageInfo

func (m *MarketChartDataPoint) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MarketChartDataPoint) GetExchangeRate() float32 {
	if m != nil {
		return m.ExchangeRate
	}
	return 0
}

type GetMarketChartResponse struct {
	Datapoints           []*MarketChartDataPoint `protobuf:"bytes,1,rep,name=datapoints,proto3" json:"datapoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetMarketChartResponse) Reset()         { *m = GetMarketChartResponse{} }
func (m *GetMarketChartResponse) String() string { return proto.CompactTextString(m) }
func (*GetMarketChartResponse) ProtoMessage()    {}
func (*GetMarketChartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{17}
}

func (m *GetMarketChartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketChartResponse.Unmarshal(m, b)
}
func (m *GetMarketChartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketChartResponse.Marshal(b, m, deterministic)
}
func (m *GetMarketChartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketChartResponse.Merge(m, src)
}
func (m *GetMarketChartResponse) XXX_Size() int {
	return xxx_messageInfo_GetMarketChartResponse.Size(m)
}
func (m *GetMarketChartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketChartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketChartResponse proto.InternalMessageInfo

func (m *GetMarketChartResponse) GetDatapoints() []*MarketChartDataPoint {
	if m != nil {
		return m.Datapoints
	}
	return nil
}

func init() {
	proto.RegisterEnum("dcrwalletgui.Network", Network_name, Network_value)
	proto.RegisterEnum("dcrwalletgui.SetConfigResponse_UpdateStatus", SetConfigResponse_UpdateStatus_name, SetConfigResponse_UpdateStatus_value)
	proto.RegisterType((*GetConfigRequest)(nil), "dcrwalletgui.GetConfigRequest")
	proto.RegisterType((*SetConfigRequest)(nil), "dcrwalletgui.SetConfigRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "dcrwalletgui.SetConfigResponse")
	proto.RegisterType((*RPCEndpoint)(nil), "dcrwalletgui.RPCEndpoint")
	proto.RegisterType((*GRPCEndpoint)(nil), "dcrwalletgui.GRPCEndpoint")
	proto.RegisterType((*AccountPreference)(nil), "dcrwalletgui.AccountPreference")
	proto.RegisterType((*WalletPreferences)(nil), "dcrwalletgui.WalletPreferences")
	proto.RegisterType((*RunTicketBuyerRequest)(nil), "dcrwalletgui.RunTicketBuyerRequest")
	proto.RegisterType((*RunAccountMixerRequest)(nil), "dcrwalletgui.RunAccountMixerRequest")
	proto.RegisterType((*AppConfiguration)(nil), "dcrwalletgui.AppConfiguration")
	proto.RegisterType((*CheckConnectionRequest)(nil), "dcrwalletgui.CheckConnectionRequest")
	proto.RegisterType((*CheckConnectionResponse)(nil), "dcrwalletgui.CheckConnectionResponse")
	proto.RegisterType((*ConnectWalletRequest)(nil), "dcrwalletgui.ConnectWalletRequest")
	proto.RegisterType((*ConnectWalletResponse)(nil), "dcrwalletgui.ConnectWalletResponse")
	proto.RegisterType((*AltCurrencyRates)(nil), "dcrwalletgui.AltCurrencyRates")
	proto.RegisterType((*AltCurrencyRates_AltCurrencyRate)(nil), "dcrwalletgui.AltCurrencyRates.AltCurrencyRate")
	proto.RegisterType((*GetMarketChartRequest)(nil), "dcrwalletgui.GetMarketChartRequest")
	proto.RegisterType((*MarketChartDataPoint)(nil), "dcrwalletgui.MarketChartDataPoint")
	proto.RegisterType((*GetMarketChartResponse)(nil), "dcrwalletgui.GetMarketChartResponse")
}

func init() { proto.RegisterFile("dcrwalletgui.proto", fileDescriptor_455734325031c3fa) }

var fileDescriptor_455734325031c3fa = []byte{
	// 1449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcb, 0x6e, 0xdb, 0xc6,
	0x1a, 0x0e, 0xe5, 0x9b, 0xf4, 0xeb, 0x62, 0x79, 0x8e, 0xed, 0xe8, 0xc8, 0x39, 0x71, 0x42, 0x27,
	0x07, 0xc6, 0x39, 0x81, 0x53, 0xb8, 0x41, 0x37, 0xbd, 0xc1, 0x96, 0x9d, 0x34, 0x68, 0xed, 0xb8,
	0x23, 0x05, 0x69, 0xd0, 0xa2, 0x83, 0x11, 0x39, 0xb6, 0x08, 0xd3, 0x24, 0x33, 0x33, 0x8c, 0x23,
	0xa0, 0xbb, 0x2e, 0xba, 0xec, 0xb2, 0x6f, 0xd0, 0x07, 0xe8, 0x43, 0x74, 0xd1, 0x17, 0xe8, 0xa2,
	0x2f, 0xd0, 0xc7, 0x28, 0xe6, 0x42, 0x9a, 0xa2, 0x9c, 0x38, 0x29, 0xba, 0xe3, 0x7c, 0xff, 0xfd,
	0x3a, 0x43, 0x40, 0xbe, 0xc7, 0xcf, 0x69, 0x18, 0x32, 0x79, 0x92, 0x06, 0x5b, 0x09, 0x8f, 0x65,
	0x8c, 0x1a, 0x45, 0xcc, 0xdd, 0x86, 0xf6, 0x23, 0x26, 0x7b, 0x71, 0x74, 0x1c, 0x9c, 0x60, 0xf6,
	0x22, 0x65, 0x42, 0xa2, 0x9b, 0x00, 0x09, 0x15, 0x22, 0x19, 0x71, 0x2a, 0x58, 0xc7, 0xb9, 0xe5,
	0x6c, 0x36, 0x70, 0x01, 0x71, 0x5f, 0x40, 0xbb, 0x5f, 0x96, 0xf9, 0x18, 0x80, 0x26, 0x09, 0xf1,
	0x34, 0xa8, 0x65, 0xea, 0xdb, 0x37, 0xb7, 0x26, 0xcc, 0xef, 0x24, 0x89, 0x91, 0x49, 0x39, 0x95,
	0x41, 0x1c, 0xe1, 0x1a, 0xcd, 0x90, 0x92, 0xc9, 0xca, 0x94, 0xc9, 0x3f, 0x1d, 0x58, 0x2a, 0xd8,
	0x14, 0x49, 0x1c, 0x09, 0x86, 0xbe, 0x84, 0x66, 0x9a, 0xf8, 0x54, 0x32, 0x22, 0x24, 0x95, 0xa9,
	0xd0, 0x76, 0x5b, 0xdb, 0xf7, 0x26, 0xed, 0x4e, 0xc9, 0x6d, 0x3d, 0xd5, 0x42, 0x7d, 0x2d, 0x83,
	0x1b, 0x69, 0xe1, 0x84, 0xfe, 0x03, 0xc0, 0x38, 0x8f, 0x39, 0xf1, 0x62, 0xdf, 0x38, 0x32, 0x87,
	0x6b, 0x1a, 0xe9, 0xc5, 0x3e, 0x43, 0xff, 0x87, 0x25, 0x43, 0xf6, 0x99, 0xf0, 0x78, 0x90, 0xa8,
	0x38, 0x3a, 0x33, 0xb7, 0x9c, 0xcd, 0x1a, 0x6e, 0x6b, 0xc2, 0xde, 0x05, 0xee, 0x3e, 0x80, 0x46,
	0xd1, 0x12, 0x42, 0xd0, 0xea, 0x0f, 0x76, 0x06, 0x4f, 0xfb, 0xa4, 0xff, 0xb4, 0xd7, 0xdb, 0xef,
	0xf7, 0xdb, 0xd7, 0x50, 0x1b, 0x1a, 0x16, 0xdb, 0xc7, 0xf8, 0x09, 0x6e, 0x3b, 0xee, 0x8f, 0x15,
	0xa8, 0xe3, 0xa3, 0xde, 0x7e, 0xe4, 0x27, 0x71, 0x10, 0x49, 0xd4, 0x82, 0x4a, 0xe0, 0xeb, 0xc8,
	0x6a, 0xb8, 0x12, 0xf8, 0xa8, 0x0b, 0xd5, 0x51, 0x2c, 0x64, 0x44, 0xcf, 0x8c, 0x7f, 0x35, 0x9c,
	0x9f, 0x11, 0x82, 0xd9, 0x24, 0xe6, 0x52, 0x7b, 0xd4, 0xc4, 0xfa, 0x5b, 0xf1, 0xa7, 0x82, 0x71,
	0xcd, 0x3f, 0x6b, 0xf8, 0xb3, 0xb3, 0xa2, 0xa9, 0x24, 0x9f, 0xc7, 0xdc, 0xef, 0xcc, 0x19, 0x5a,
	0x76, 0x46, 0x77, 0xa0, 0xe5, 0x31, 0x2e, 0xc9, 0x71, 0x10, 0x32, 0xa2, 0xa5, 0xe7, 0x35, 0x47,
	0x43, 0xa1, 0x0f, 0x83, 0x90, 0x1d, 0x2a, 0x0d, 0x6b, 0x50, 0xd3, 0x5c, 0xc3, 0x30, 0x1e, 0x76,
	0x16, 0x8c, 0x0a, 0x05, 0xec, 0x86, 0xf1, 0x10, 0xdd, 0x87, 0x85, 0x88, 0xc9, 0xf3, 0x98, 0x9f,
	0x76, 0xaa, 0xba, 0x32, 0x2b, 0x93, 0x95, 0x39, 0x34, 0x44, 0x9c, 0x71, 0xa1, 0x65, 0x98, 0x0b,
	0xe9, 0x90, 0x85, 0x9d, 0x9a, 0xd6, 0x64, 0x0e, 0xee, 0xaf, 0x15, 0x68, 0x3c, 0xfa, 0x27, 0x53,
	0x32, 0x1d, 0xda, 0xec, 0x55, 0xa1, 0xcd, 0xbd, 0x3e, 0xb4, 0xf9, 0x77, 0x0b, 0x6d, 0xa1, 0x10,
	0x1a, 0xda, 0x84, 0x76, 0x20, 0xc8, 0x39, 0x95, 0xde, 0x28, 0x88, 0x4e, 0x48, 0x1c, 0x85, 0x63,
	0x9d, 0xaa, 0x2a, 0x6e, 0x05, 0xe2, 0x99, 0x85, 0x9f, 0x44, 0xe1, 0x18, 0xdd, 0x85, 0x16, 0xf5,
	0x64, 0xf0, 0x92, 0x91, 0xcc, 0x6e, 0x4d, 0x47, 0xd4, 0x34, 0xa8, 0xb5, 0xa7, 0x9d, 0x8e, 0x83,
	0x88, 0xc8, 0x71, 0xc2, 0x3a, 0xa0, 0x39, 0xaa, 0x0a, 0x18, 0x8c, 0x13, 0xe6, 0x7e, 0x07, 0x4b,
	0x3b, 0x9e, 0x17, 0xa7, 0x91, 0x3c, 0xe2, 0xec, 0x98, 0x71, 0x16, 0x79, 0xcc, 0x28, 0xd6, 0x20,
	0x89, 0xd2, 0xb3, 0x21, 0xe3, 0x3a, 0xb1, 0x5a, 0xb1, 0x46, 0x0f, 0x35, 0xa8, 0x14, 0x07, 0x82,
	0x8c, 0x02, 0xdf, 0x67, 0x91, 0x4e, 0x72, 0x15, 0x57, 0x03, 0xf1, 0x99, 0x3e, 0xa3, 0x0d, 0x68,
	0xfa, 0x81, 0x48, 0x42, 0x3a, 0x26, 0x31, 0xf7, 0x19, 0xb7, 0xd9, 0x6e, 0x58, 0xf0, 0x89, 0xc2,
	0xdc, 0x1f, 0x1c, 0x58, 0x7a, 0xa6, 0x13, 0x74, 0x61, 0x5d, 0xa0, 0x7b, 0x80, 0x4c, 0xd6, 0x08,
	0xb3, 0xe5, 0x25, 0x79, 0x6d, 0xdb, 0x86, 0x92, 0xd5, 0xfd, 0xb1, 0x8f, 0xf6, 0x20, 0x73, 0x8b,
	0x24, 0x9c, 0x1d, 0x8b, 0x4e, 0xe5, 0xd6, 0xcc, 0x66, 0x7d, 0x7b, 0xbd, 0xb4, 0x69, 0xca, 0x41,
	0xe2, 0x06, 0xbd, 0x80, 0x84, 0x1a, 0xb1, 0x15, 0x9c, 0x46, 0x83, 0xc0, 0x3b, 0x65, 0x72, 0x37,
	0x1d, 0x33, 0xfe, 0x96, 0xab, 0x0f, 0x75, 0x60, 0xc1, 0x6a, 0xd2, 0x39, 0x68, 0xe2, 0xec, 0xa8,
	0xd2, 0xf8, 0x32, 0x96, 0xaa, 0x88, 0x19, 0x83, 0xc9, 0x41, 0xd3, 0xa0, 0xd6, 0x25, 0xb4, 0x05,
	0xff, 0x1a, 0xd2, 0x90, 0x46, 0x1e, 0x23, 0x32, 0x26, 0x67, 0x34, 0x88, 0x24, 0x0d, 0x22, 0xdd,
	0x7f, 0x33, 0x78, 0xc9, 0x92, 0x06, 0xf1, 0x81, 0x25, 0x14, 0xd5, 0xfa, 0x3e, 0x67, 0x42, 0xd8,
	0x4e, 0xcc, 0xd4, 0x1a, 0x10, 0xdd, 0x86, 0x46, 0x12, 0xc7, 0x61, 0xce, 0x64, 0x46, 0xb5, 0xae,
	0xb0, 0x8c, 0x65, 0x0d, 0x6a, 0x9a, 0xe5, 0x98, 0x31, 0xa1, 0x9b, 0xd0, 0xc1, 0x55, 0x05, 0x3c,
	0x64, 0x4c, 0xb8, 0xbf, 0x3b, 0xb0, 0x8a, 0xd3, 0xc8, 0x7a, 0x79, 0x10, 0xbc, 0x7a, 0xfb, 0x94,
	0x6c, 0x40, 0xf3, 0x2c, 0x78, 0xc5, 0x7c, 0x32, 0x99, 0x98, 0x86, 0x06, 0xb3, 0xb0, 0xdf, 0x83,
	0xe5, 0x09, 0x26, 0x32, 0xe4, 0x34, 0xf2, 0x46, 0x36, 0x47, 0xa8, 0xc8, 0xbb, 0xab, 0x29, 0x2a,
	0x70, 0x6f, 0x44, 0xa3, 0x13, 0x96, 0xeb, 0x9d, 0x35, 0xf9, 0x34, 0x68, 0xa6, 0x78, 0x1d, 0xea,
	0x9e, 0x48, 0x12, 0x22, 0x18, 0x7f, 0xc9, 0xb8, 0x4d, 0x0e, 0x28, 0xa8, 0xaf, 0x11, 0xf7, 0x97,
	0x59, 0x68, 0x97, 0x6f, 0x1e, 0xf4, 0x09, 0x34, 0x7d, 0x8f, 0xfb, 0x79, 0xcb, 0xd9, 0x0b, 0xeb,
	0xdf, 0x93, 0x6d, 0x54, 0x58, 0x39, 0x58, 0xdd, 0x9a, 0x7e, 0xbe, 0x80, 0xf6, 0xa1, 0x5d, 0x6a,
	0xda, 0xac, 0x13, 0xbb, 0x93, 0x2a, 0x8a, 0x6b, 0x0b, 0x2f, 0x4e, 0xb6, 0xb3, 0x40, 0x1f, 0x42,
	0xd7, 0x67, 0xc7, 0x34, 0x0d, 0x25, 0xb9, 0x64, 0x06, 0xcc, 0xb5, 0x72, 0xdd, 0x72, 0x3c, 0x2b,
	0x8f, 0xc2, 0x61, 0x3e, 0x38, 0xc9, 0xc5, 0x38, 0x75, 0x66, 0x2f, 0x9b, 0x87, 0xa9, 0xa9, 0xc3,
	0x4b, 0xe7, 0x53, 0x83, 0x18, 0xc0, 0xcd, 0xac, 0x38, 0xaa, 0x1c, 0x9c, 0x70, 0xd3, 0x00, 0xc4,
	0x3a, 0x60, 0x3a, 0xaf, 0xbe, 0x7d, 0xa7, 0x94, 0xa4, 0x4b, 0xbb, 0x06, 0xaf, 0xd1, 0x69, 0x70,
	0xcf, 0x2a, 0x42, 0x01, 0xac, 0xf3, 0x34, 0x22, 0x34, 0x95, 0x31, 0x19, 0xaa, 0xf1, 0x9b, 0xb6,
	0x35, 0xaf, 0x6d, 0x6d, 0x4c, 0xd9, 0x9a, 0x9e, 0x59, 0xbc, 0xc6, 0xd3, 0x68, 0x27, 0x95, 0x71,
	0x11, 0xcc, 0x4d, 0x3d, 0x80, 0x55, 0x1a, 0x4a, 0x92, 0x6d, 0x27, 0x2f, 0xe5, 0x2a, 0xdc, 0x40,
	0x8f, 0xc0, 0xcc, 0x66, 0x0d, 0x2f, 0xd3, 0x50, 0xee, 0x19, 0x62, 0x2f, 0xa7, 0xb9, 0x3f, 0x39,
	0xb0, 0xda, 0x1b, 0x31, 0xef, 0xb4, 0x17, 0x47, 0x11, 0xf3, 0xf4, 0x6b, 0xc5, 0x8e, 0xc3, 0xa7,
	0xd0, 0x3c, 0xe1, 0x89, 0x57, 0x6e, 0x9d, 0x37, 0xd5, 0xbd, 0xa1, 0x04, 0xf2, 0xde, 0xf9, 0x08,
	0x1a, 0x13, 0xf2, 0x95, 0xab, 0x5a, 0xaf, 0x5e, 0x90, 0x76, 0x0f, 0xe0, 0xfa, 0x94, 0x63, 0xf6,
	0x35, 0x74, 0x43, 0x6d, 0xe8, 0x7e, 0xea, 0x79, 0x6a, 0x01, 0x38, 0x7a, 0x43, 0x5f, 0x00, 0xea,
	0xfe, 0xd1, 0x0f, 0x14, 0x7b, 0x41, 0x9a, 0x83, 0xbb, 0x07, 0xcb, 0x56, 0x93, 0xe9, 0x91, 0x2c,
	0xca, 0x77, 0xda, 0xca, 0xee, 0xf7, 0x0e, 0xac, 0x94, 0xd4, 0xfc, 0x7d, 0x9f, 0xd0, 0x07, 0x50,
	0xcd, 0x93, 0x33, 0x73, 0x65, 0x72, 0x73, 0x5e, 0xf7, 0x0f, 0x07, 0xda, 0x3b, 0xa1, 0xb4, 0x65,
	0x1c, 0x63, 0x2a, 0x99, 0x40, 0x7b, 0x30, 0xc7, 0xd5, 0x47, 0xc7, 0xd1, 0x83, 0xb1, 0x55, 0xba,
	0x28, 0x4a, 0xec, 0x65, 0x00, 0x1b, 0x61, 0xf4, 0x5f, 0x58, 0x0c, 0xa9, 0x90, 0xc4, 0x3c, 0x15,
	0x7d, 0xa2, 0xc7, 0x5d, 0x6d, 0xec, 0xa6, 0x82, 0xcd, 0x23, 0xcf, 0x1f, 0x88, 0xee, 0x73, 0x58,
	0x2c, 0x69, 0x50, 0xeb, 0xd1, 0x36, 0xdd, 0xd8, 0xbc, 0x29, 0x1d, 0xfb, 0xd4, 0xb0, 0xa0, 0x7e,
	0x56, 0xde, 0x06, 0x7b, 0x96, 0x44, 0x19, 0xd4, 0xca, 0x2b, 0xb8, 0x6e, 0x31, 0xa5, 0xc7, 0x3d,
	0x82, 0x95, 0x47, 0x4c, 0x1e, 0x50, 0x7e, 0xca, 0x64, 0x6f, 0x44, 0x79, 0x5e, 0xaa, 0xb7, 0x32,
	0x80, 0x60, 0xd6, 0xa7, 0x63, 0x61, 0x77, 0xb3, 0xfe, 0x76, 0x9f, 0xc3, 0x72, 0x41, 0xdd, 0x1e,
	0x95, 0xf4, 0x48, 0x37, 0xe8, 0x0d, 0xa8, 0xc9, 0xe0, 0x8c, 0x09, 0x49, 0xcf, 0x12, 0xad, 0x6c,
	0x06, 0x5f, 0x00, 0xca, 0x1c, 0x7b, 0x65, 0x37, 0x73, 0xc1, 0xd7, 0x46, 0x06, 0x6a, 0x67, 0xbf,
	0x81, 0xd5, 0xb2, 0xb3, 0xb6, 0x21, 0x76, 0x01, 0x7c, 0x2a, 0xa9, 0xdd, 0x99, 0xa6, 0x28, 0xee,
	0x64, 0x51, 0x2e, 0x73, 0x0a, 0x17, 0xa4, 0xfe, 0x77, 0x1f, 0x16, 0xb2, 0xe7, 0x4e, 0x1d, 0x16,
	0x0e, 0x76, 0x1e, 0x1f, 0x1e, 0xee, 0x0f, 0xda, 0xd7, 0xd4, 0x61, 0xb0, 0xdf, 0x1f, 0xa8, 0x83,
	0x83, 0x00, 0xe6, 0xfb, 0x8f, 0x0f, 0xd4, 0x77, 0x65, 0xfb, 0x67, 0x07, 0x6a, 0xf9, 0x1d, 0x80,
	0x3e, 0x87, 0x5a, 0xfe, 0xcb, 0x83, 0x4a, 0xff, 0x28, 0xe5, 0x7f, 0xa1, 0xee, 0x15, 0xff, 0x30,
	0xe8, 0x0b, 0xa8, 0xf5, 0x5f, 0xa7, 0xac, 0xfc, 0x93, 0xd4, 0x5d, 0xbf, 0xe2, 0xc7, 0x64, 0xfb,
	0x37, 0x07, 0x5a, 0x36, 0x34, 0x75, 0x7d, 0x05, 0x1e, 0x43, 0xdf, 0xc2, 0x62, 0x69, 0xe0, 0x51,
	0x69, 0x03, 0x5f, 0xbe, 0xa8, 0xba, 0x77, 0xaf, 0xe0, 0xb2, 0x05, 0xf9, 0x0a, 0x9a, 0x13, 0xa3,
	0x8b, 0x4a, 0xd5, 0xb8, 0x6c, 0x3d, 0x74, 0x37, 0xde, 0xc8, 0x63, 0x83, 0x09, 0xa1, 0xb9, 0x5f,
	0x68, 0x0a, 0x81, 0xbe, 0x86, 0xd6, 0x64, 0x57, 0xa0, 0x8d, 0xa9, 0xec, 0x4f, 0x37, 0x78, 0xf7,
	0xce, 0x9b, 0x99, 0x8c, 0xb5, 0xe1, 0xbc, 0xfe, 0xbb, 0x7d, 0xff, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xad, 0xa7, 0x7b, 0x2f, 0xf3, 0x0e, 0x00, 0x00,
}
