// Code generated by protoc-gen-go. DO NOT EDIT.
// source: walletgui.proto

package walletgui

import (
	walletrpc "decred.org/dcrwallet/rpc/walletrpc"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Network int32

const (
	Network_MAINNET Network = 0
	Network_TESTNET Network = 1
	Network_SIMNET  Network = 2
)

var Network_name = map[int32]string{
	0: "MAINNET",
	1: "TESTNET",
	2: "SIMNET",
}

var Network_value = map[string]int32{
	"MAINNET": 0,
	"TESTNET": 1,
	"SIMNET":  2,
}

func (x Network) String() string {
	return proto.EnumName(Network_name, int32(x))
}

func (Network) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{0}
}

type DisplayUnit int32

const (
	DisplayUnit_DCR   DisplayUnit = 0
	DisplayUnit_ATOMS DisplayUnit = 1
)

var DisplayUnit_name = map[int32]string{
	0: "DCR",
	1: "ATOMS",
}

var DisplayUnit_value = map[string]int32{
	"DCR":   0,
	"ATOMS": 1,
}

func (x DisplayUnit) String() string {
	return proto.EnumName(DisplayUnit_name, int32(x))
}

func (DisplayUnit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{1}
}

type FiatCurrency int32

const (
	FiatCurrency_USD FiatCurrency = 0
	FiatCurrency_EUR FiatCurrency = 1
)

var FiatCurrency_name = map[int32]string{
	0: "USD",
	1: "EUR",
}

var FiatCurrency_value = map[string]int32{
	"USD": 0,
	"EUR": 1,
}

func (x FiatCurrency) String() string {
	return proto.EnumName(FiatCurrency_name, int32(x))
}

func (FiatCurrency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{2}
}

type Theme int32

const (
	Theme_LIGHT Theme = 0
	Theme_DARK  Theme = 1
)

var Theme_name = map[int32]string{
	0: "LIGHT",
	1: "DARK",
}

var Theme_value = map[string]int32{
	"LIGHT": 0,
	"DARK":  1,
}

func (x Theme) String() string {
	return proto.EnumName(Theme_name, int32(x))
}

func (Theme) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{3}
}

type SetConfigResponse_UpdateStatus int32

const (
	SetConfigResponse_STATUS_SUCCESS SetConfigResponse_UpdateStatus = 0
	SetConfigResponse_STATUS_ERROR   SetConfigResponse_UpdateStatus = 1
)

var SetConfigResponse_UpdateStatus_name = map[int32]string{
	0: "STATUS_SUCCESS",
	1: "STATUS_ERROR",
}

var SetConfigResponse_UpdateStatus_value = map[string]int32{
	"STATUS_SUCCESS": 0,
	"STATUS_ERROR":   1,
}

func (x SetConfigResponse_UpdateStatus) String() string {
	return proto.EnumName(SetConfigResponse_UpdateStatus_name, int32(x))
}

func (SetConfigResponse_UpdateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{2, 0}
}

type GetConfigRequest struct {
	Passphrase           []byte   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{0}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

type SetConfigRequest struct {
	AppConfig            *AppConfiguration `protobuf:"bytes,1,opt,name=app_config,json=appConfig,proto3" json:"app_config,omitempty"`
	Passphrase           string            `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{1}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetAppConfig() *AppConfiguration {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

func (m *SetConfigRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type SetConfigResponse struct {
	UpdateStatus         SetConfigResponse_UpdateStatus `protobuf:"varint,1,opt,name=update_status,json=updateStatus,proto3,enum=walletgui.SetConfigResponse_UpdateStatus" json:"update_status,omitempty"`
	ErrorCode            int32                          `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorDescription     string                         `protobuf:"bytes,3,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SetConfigResponse) Reset()         { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()    {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{2}
}

func (m *SetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigResponse.Unmarshal(m, b)
}
func (m *SetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigResponse.Merge(m, src)
}
func (m *SetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigResponse.Size(m)
}
func (m *SetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigResponse proto.InternalMessageInfo

func (m *SetConfigResponse) GetUpdateStatus() SetConfigResponse_UpdateStatus {
	if m != nil {
		return m.UpdateStatus
	}
	return SetConfigResponse_STATUS_SUCCESS
}

func (m *SetConfigResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *SetConfigResponse) GetErrorDescription() string {
	if m != nil {
		return m.ErrorDescription
	}
	return ""
}

type RPCEndpoint struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	CertFileName         string   `protobuf:"bytes,6,opt,name=cert_file_name,json=certFileName,proto3" json:"cert_file_name,omitempty"`
	CertBlob             string   `protobuf:"bytes,7,opt,name=cert_blob,json=certBlob,proto3" json:"cert_blob,omitempty"`
	Network              Network  `protobuf:"varint,8,opt,name=network,proto3,enum=walletgui.Network" json:"network,omitempty"`
	Label                string   `protobuf:"bytes,9,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCEndpoint) Reset()         { *m = RPCEndpoint{} }
func (m *RPCEndpoint) String() string { return proto.CompactTextString(m) }
func (*RPCEndpoint) ProtoMessage()    {}
func (*RPCEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{3}
}

func (m *RPCEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCEndpoint.Unmarshal(m, b)
}
func (m *RPCEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCEndpoint.Marshal(b, m, deterministic)
}
func (m *RPCEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCEndpoint.Merge(m, src)
}
func (m *RPCEndpoint) XXX_Size() int {
	return xxx_messageInfo_RPCEndpoint.Size(m)
}
func (m *RPCEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_RPCEndpoint proto.InternalMessageInfo

func (m *RPCEndpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RPCEndpoint) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RPCEndpoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RPCEndpoint) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RPCEndpoint) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RPCEndpoint) GetCertFileName() string {
	if m != nil {
		return m.CertFileName
	}
	return ""
}

func (m *RPCEndpoint) GetCertBlob() string {
	if m != nil {
		return m.CertBlob
	}
	return ""
}

func (m *RPCEndpoint) GetNetwork() Network {
	if m != nil {
		return m.Network
	}
	return Network_MAINNET
}

func (m *RPCEndpoint) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type GRPCEndpoint struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	CertFileName         string   `protobuf:"bytes,4,opt,name=cert_file_name,json=certFileName,proto3" json:"cert_file_name,omitempty"`
	CertBlob             string   `protobuf:"bytes,5,opt,name=cert_blob,json=certBlob,proto3" json:"cert_blob,omitempty"`
	Network              Network  `protobuf:"varint,6,opt,name=network,proto3,enum=walletgui.Network" json:"network,omitempty"`
	Label                string   `protobuf:"bytes,7,opt,name=label,proto3" json:"label,omitempty"`
	IsWatchingOnly       bool     `protobuf:"varint,8,opt,name=is_watching_only,json=isWatchingOnly,proto3" json:"is_watching_only,omitempty"`
	ActiveNetwork        uint32   `protobuf:"varint,9,opt,name=active_network,json=activeNetwork,proto3" json:"active_network,omitempty"`
	CoinType             uint32   `protobuf:"varint,10,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`
	ClientCertBlob       string   `protobuf:"bytes,11,opt,name=client_cert_blob,json=clientCertBlob,proto3" json:"client_cert_blob,omitempty"`
	ClientKeyBlob        string   `protobuf:"bytes,12,opt,name=client_key_blob,json=clientKeyBlob,proto3" json:"client_key_blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GRPCEndpoint) Reset()         { *m = GRPCEndpoint{} }
func (m *GRPCEndpoint) String() string { return proto.CompactTextString(m) }
func (*GRPCEndpoint) ProtoMessage()    {}
func (*GRPCEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{4}
}

func (m *GRPCEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GRPCEndpoint.Unmarshal(m, b)
}
func (m *GRPCEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GRPCEndpoint.Marshal(b, m, deterministic)
}
func (m *GRPCEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GRPCEndpoint.Merge(m, src)
}
func (m *GRPCEndpoint) XXX_Size() int {
	return xxx_messageInfo_GRPCEndpoint.Size(m)
}
func (m *GRPCEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_GRPCEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_GRPCEndpoint proto.InternalMessageInfo

func (m *GRPCEndpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GRPCEndpoint) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *GRPCEndpoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GRPCEndpoint) GetCertFileName() string {
	if m != nil {
		return m.CertFileName
	}
	return ""
}

func (m *GRPCEndpoint) GetCertBlob() string {
	if m != nil {
		return m.CertBlob
	}
	return ""
}

func (m *GRPCEndpoint) GetNetwork() Network {
	if m != nil {
		return m.Network
	}
	return Network_MAINNET
}

func (m *GRPCEndpoint) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *GRPCEndpoint) GetIsWatchingOnly() bool {
	if m != nil {
		return m.IsWatchingOnly
	}
	return false
}

func (m *GRPCEndpoint) GetActiveNetwork() uint32 {
	if m != nil {
		return m.ActiveNetwork
	}
	return 0
}

func (m *GRPCEndpoint) GetCoinType() uint32 {
	if m != nil {
		return m.CoinType
	}
	return 0
}

func (m *GRPCEndpoint) GetClientCertBlob() string {
	if m != nil {
		return m.ClientCertBlob
	}
	return ""
}

func (m *GRPCEndpoint) GetClientKeyBlob() string {
	if m != nil {
		return m.ClientKeyBlob
	}
	return ""
}

type AppConfiguration struct {
	WalletEndpoints         []*GRPCEndpoint                                `protobuf:"bytes,1,rep,name=wallet_endpoints,json=walletEndpoints,proto3" json:"wallet_endpoints,omitempty"`
	DefaultWalletEndpointId string                                         `protobuf:"bytes,2,opt,name=default_wallet_endpoint_id,json=defaultWalletEndpointId,proto3" json:"default_wallet_endpoint_id,omitempty"`
	WalletPreferences       map[string]*AppConfiguration_WalletPreferences `protobuf:"bytes,3,rep,name=wallet_preferences,json=walletPreferences,proto3" json:"wallet_preferences,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AltDisplayCurrencies    []string                                       `protobuf:"bytes,4,rep,name=alt_display_currencies,json=altDisplayCurrencies,proto3" json:"alt_display_currencies,omitempty"`
	UiPreferences           *AppConfiguration_UIPreferences                `protobuf:"bytes,5,opt,name=ui_preferences,json=uiPreferences,proto3" json:"ui_preferences,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                                       `json:"-"`
	XXX_unrecognized        []byte                                         `json:"-"`
	XXX_sizecache           int32                                          `json:"-"`
}

func (m *AppConfiguration) Reset()         { *m = AppConfiguration{} }
func (m *AppConfiguration) String() string { return proto.CompactTextString(m) }
func (*AppConfiguration) ProtoMessage()    {}
func (*AppConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{5}
}

func (m *AppConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfiguration.Unmarshal(m, b)
}
func (m *AppConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfiguration.Marshal(b, m, deterministic)
}
func (m *AppConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfiguration.Merge(m, src)
}
func (m *AppConfiguration) XXX_Size() int {
	return xxx_messageInfo_AppConfiguration.Size(m)
}
func (m *AppConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfiguration proto.InternalMessageInfo

func (m *AppConfiguration) GetWalletEndpoints() []*GRPCEndpoint {
	if m != nil {
		return m.WalletEndpoints
	}
	return nil
}

func (m *AppConfiguration) GetDefaultWalletEndpointId() string {
	if m != nil {
		return m.DefaultWalletEndpointId
	}
	return ""
}

func (m *AppConfiguration) GetWalletPreferences() map[string]*AppConfiguration_WalletPreferences {
	if m != nil {
		return m.WalletPreferences
	}
	return nil
}

func (m *AppConfiguration) GetAltDisplayCurrencies() []string {
	if m != nil {
		return m.AltDisplayCurrencies
	}
	return nil
}

func (m *AppConfiguration) GetUiPreferences() *AppConfiguration_UIPreferences {
	if m != nil {
		return m.UiPreferences
	}
	return nil
}

type AppConfiguration_UIPreferences struct {
	DisplayUnit          DisplayUnit  `protobuf:"varint,1,opt,name=display_unit,json=displayUnit,proto3,enum=walletgui.DisplayUnit" json:"display_unit,omitempty"`
	FiatCurrency         FiatCurrency `protobuf:"varint,2,opt,name=fiat_currency,json=fiatCurrency,proto3,enum=walletgui.FiatCurrency" json:"fiat_currency,omitempty"`
	IsConfigEncrypted    bool         `protobuf:"varint,3,opt,name=is_config_encrypted,json=isConfigEncrypted,proto3" json:"is_config_encrypted,omitempty"`
	Theme                Theme        `protobuf:"varint,4,opt,name=theme,proto3,enum=walletgui.Theme" json:"theme,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AppConfiguration_UIPreferences) Reset()         { *m = AppConfiguration_UIPreferences{} }
func (m *AppConfiguration_UIPreferences) String() string { return proto.CompactTextString(m) }
func (*AppConfiguration_UIPreferences) ProtoMessage()    {}
func (*AppConfiguration_UIPreferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{5, 0}
}

func (m *AppConfiguration_UIPreferences) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfiguration_UIPreferences.Unmarshal(m, b)
}
func (m *AppConfiguration_UIPreferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfiguration_UIPreferences.Marshal(b, m, deterministic)
}
func (m *AppConfiguration_UIPreferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfiguration_UIPreferences.Merge(m, src)
}
func (m *AppConfiguration_UIPreferences) XXX_Size() int {
	return xxx_messageInfo_AppConfiguration_UIPreferences.Size(m)
}
func (m *AppConfiguration_UIPreferences) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfiguration_UIPreferences.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfiguration_UIPreferences proto.InternalMessageInfo

func (m *AppConfiguration_UIPreferences) GetDisplayUnit() DisplayUnit {
	if m != nil {
		return m.DisplayUnit
	}
	return DisplayUnit_DCR
}

func (m *AppConfiguration_UIPreferences) GetFiatCurrency() FiatCurrency {
	if m != nil {
		return m.FiatCurrency
	}
	return FiatCurrency_USD
}

func (m *AppConfiguration_UIPreferences) GetIsConfigEncrypted() bool {
	if m != nil {
		return m.IsConfigEncrypted
	}
	return false
}

func (m *AppConfiguration_UIPreferences) GetTheme() Theme {
	if m != nil {
		return m.Theme
	}
	return Theme_LIGHT
}

type AppConfiguration_AccountPreference struct {
	IsHidden             bool     `protobuf:"varint,1,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	DisplayOrder         uint32   `protobuf:"varint,2,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppConfiguration_AccountPreference) Reset()         { *m = AppConfiguration_AccountPreference{} }
func (m *AppConfiguration_AccountPreference) String() string { return proto.CompactTextString(m) }
func (*AppConfiguration_AccountPreference) ProtoMessage()    {}
func (*AppConfiguration_AccountPreference) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{5, 1}
}

func (m *AppConfiguration_AccountPreference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfiguration_AccountPreference.Unmarshal(m, b)
}
func (m *AppConfiguration_AccountPreference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfiguration_AccountPreference.Marshal(b, m, deterministic)
}
func (m *AppConfiguration_AccountPreference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfiguration_AccountPreference.Merge(m, src)
}
func (m *AppConfiguration_AccountPreference) XXX_Size() int {
	return xxx_messageInfo_AppConfiguration_AccountPreference.Size(m)
}
func (m *AppConfiguration_AccountPreference) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfiguration_AccountPreference.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfiguration_AccountPreference proto.InternalMessageInfo

func (m *AppConfiguration_AccountPreference) GetIsHidden() bool {
	if m != nil {
		return m.IsHidden
	}
	return false
}

func (m *AppConfiguration_AccountPreference) GetDisplayOrder() uint32 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

type AppConfiguration_WalletPreferences struct {
	AccountPrefs                map[uint32]*AppConfiguration_AccountPreference `protobuf:"bytes,1,rep,name=account_prefs,json=accountPrefs,proto3" json:"account_prefs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AccountMixerRequestDefaults *walletrpc.RunAccountMixerRequest              `protobuf:"bytes,2,opt,name=account_mixer_request_defaults,json=accountMixerRequestDefaults,proto3" json:"account_mixer_request_defaults,omitempty"`
	RunAutoBuyerRequestDefaults *walletrpc.RunTicketBuyerRequest               `protobuf:"bytes,3,opt,name=run_auto_buyer_request_defaults,json=runAutoBuyerRequestDefaults,proto3" json:"run_auto_buyer_request_defaults,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                                       `json:"-"`
	XXX_unrecognized            []byte                                         `json:"-"`
	XXX_sizecache               int32                                          `json:"-"`
}

func (m *AppConfiguration_WalletPreferences) Reset()         { *m = AppConfiguration_WalletPreferences{} }
func (m *AppConfiguration_WalletPreferences) String() string { return proto.CompactTextString(m) }
func (*AppConfiguration_WalletPreferences) ProtoMessage()    {}
func (*AppConfiguration_WalletPreferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{5, 2}
}

func (m *AppConfiguration_WalletPreferences) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfiguration_WalletPreferences.Unmarshal(m, b)
}
func (m *AppConfiguration_WalletPreferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfiguration_WalletPreferences.Marshal(b, m, deterministic)
}
func (m *AppConfiguration_WalletPreferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfiguration_WalletPreferences.Merge(m, src)
}
func (m *AppConfiguration_WalletPreferences) XXX_Size() int {
	return xxx_messageInfo_AppConfiguration_WalletPreferences.Size(m)
}
func (m *AppConfiguration_WalletPreferences) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfiguration_WalletPreferences.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfiguration_WalletPreferences proto.InternalMessageInfo

func (m *AppConfiguration_WalletPreferences) GetAccountPrefs() map[uint32]*AppConfiguration_AccountPreference {
	if m != nil {
		return m.AccountPrefs
	}
	return nil
}

func (m *AppConfiguration_WalletPreferences) GetAccountMixerRequestDefaults() *walletrpc.RunAccountMixerRequest {
	if m != nil {
		return m.AccountMixerRequestDefaults
	}
	return nil
}

func (m *AppConfiguration_WalletPreferences) GetRunAutoBuyerRequestDefaults() *walletrpc.RunTicketBuyerRequest {
	if m != nil {
		return m.RunAutoBuyerRequestDefaults
	}
	return nil
}

type CheckConnectionRequest struct {
	GrpcEndpoint         *GRPCEndpoint `protobuf:"bytes,1,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	RpcEndpoint          *RPCEndpoint  `protobuf:"bytes,2,opt,name=rpc_endpoint,json=rpcEndpoint,proto3" json:"rpc_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CheckConnectionRequest) Reset()         { *m = CheckConnectionRequest{} }
func (m *CheckConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*CheckConnectionRequest) ProtoMessage()    {}
func (*CheckConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{6}
}

func (m *CheckConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckConnectionRequest.Unmarshal(m, b)
}
func (m *CheckConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckConnectionRequest.Marshal(b, m, deterministic)
}
func (m *CheckConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckConnectionRequest.Merge(m, src)
}
func (m *CheckConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_CheckConnectionRequest.Size(m)
}
func (m *CheckConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckConnectionRequest proto.InternalMessageInfo

func (m *CheckConnectionRequest) GetGrpcEndpoint() *GRPCEndpoint {
	if m != nil {
		return m.GrpcEndpoint
	}
	return nil
}

func (m *CheckConnectionRequest) GetRpcEndpoint() *RPCEndpoint {
	if m != nil {
		return m.RpcEndpoint
	}
	return nil
}

type CheckConnectionResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckConnectionResponse) Reset()         { *m = CheckConnectionResponse{} }
func (m *CheckConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*CheckConnectionResponse) ProtoMessage()    {}
func (*CheckConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{7}
}

func (m *CheckConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckConnectionResponse.Unmarshal(m, b)
}
func (m *CheckConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckConnectionResponse.Marshal(b, m, deterministic)
}
func (m *CheckConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckConnectionResponse.Merge(m, src)
}
func (m *CheckConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_CheckConnectionResponse.Size(m)
}
func (m *CheckConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckConnectionResponse proto.InternalMessageInfo

func (m *CheckConnectionResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *CheckConnectionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ConnectWalletRequest struct {
	WalletEndpointId     string   `protobuf:"bytes,1,opt,name=wallet_endpoint_id,json=walletEndpointId,proto3" json:"wallet_endpoint_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectWalletRequest) Reset()         { *m = ConnectWalletRequest{} }
func (m *ConnectWalletRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectWalletRequest) ProtoMessage()    {}
func (*ConnectWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{8}
}

func (m *ConnectWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectWalletRequest.Unmarshal(m, b)
}
func (m *ConnectWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectWalletRequest.Marshal(b, m, deterministic)
}
func (m *ConnectWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectWalletRequest.Merge(m, src)
}
func (m *ConnectWalletRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectWalletRequest.Size(m)
}
func (m *ConnectWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectWalletRequest proto.InternalMessageInfo

func (m *ConnectWalletRequest) GetWalletEndpointId() string {
	if m != nil {
		return m.WalletEndpointId
	}
	return ""
}

type ConnectWalletResponse struct {
	IsSuccess            bool          `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	Error                string        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Endpoint             *GRPCEndpoint `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConnectWalletResponse) Reset()         { *m = ConnectWalletResponse{} }
func (m *ConnectWalletResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectWalletResponse) ProtoMessage()    {}
func (*ConnectWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{9}
}

func (m *ConnectWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectWalletResponse.Unmarshal(m, b)
}
func (m *ConnectWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectWalletResponse.Marshal(b, m, deterministic)
}
func (m *ConnectWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectWalletResponse.Merge(m, src)
}
func (m *ConnectWalletResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectWalletResponse.Size(m)
}
func (m *ConnectWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectWalletResponse proto.InternalMessageInfo

func (m *ConnectWalletResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *ConnectWalletResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ConnectWalletResponse) GetEndpoint() *GRPCEndpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

// exchange rates
type AltCurrencyRates struct {
	Rates                []*AltCurrencyRates_AltCurrencyRate `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	LastUpdatedTs        int64                               `protobuf:"varint,2,opt,name=last_updated_ts,json=lastUpdatedTs,proto3" json:"last_updated_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *AltCurrencyRates) Reset()         { *m = AltCurrencyRates{} }
func (m *AltCurrencyRates) String() string { return proto.CompactTextString(m) }
func (*AltCurrencyRates) ProtoMessage()    {}
func (*AltCurrencyRates) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{10}
}

func (m *AltCurrencyRates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AltCurrencyRates.Unmarshal(m, b)
}
func (m *AltCurrencyRates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AltCurrencyRates.Marshal(b, m, deterministic)
}
func (m *AltCurrencyRates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AltCurrencyRates.Merge(m, src)
}
func (m *AltCurrencyRates) XXX_Size() int {
	return xxx_messageInfo_AltCurrencyRates.Size(m)
}
func (m *AltCurrencyRates) XXX_DiscardUnknown() {
	xxx_messageInfo_AltCurrencyRates.DiscardUnknown(m)
}

var xxx_messageInfo_AltCurrencyRates proto.InternalMessageInfo

func (m *AltCurrencyRates) GetRates() []*AltCurrencyRates_AltCurrencyRate {
	if m != nil {
		return m.Rates
	}
	return nil
}

func (m *AltCurrencyRates) GetLastUpdatedTs() int64 {
	if m != nil {
		return m.LastUpdatedTs
	}
	return 0
}

type AltCurrencyRates_AltCurrencyRate struct {
	CurrencyCode         string   `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CurrentRate          float32  `protobuf:"fixed32,2,opt,name=current_rate,json=currentRate,proto3" json:"current_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AltCurrencyRates_AltCurrencyRate) Reset()         { *m = AltCurrencyRates_AltCurrencyRate{} }
func (m *AltCurrencyRates_AltCurrencyRate) String() string { return proto.CompactTextString(m) }
func (*AltCurrencyRates_AltCurrencyRate) ProtoMessage()    {}
func (*AltCurrencyRates_AltCurrencyRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{10, 0}
}

func (m *AltCurrencyRates_AltCurrencyRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AltCurrencyRates_AltCurrencyRate.Unmarshal(m, b)
}
func (m *AltCurrencyRates_AltCurrencyRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AltCurrencyRates_AltCurrencyRate.Marshal(b, m, deterministic)
}
func (m *AltCurrencyRates_AltCurrencyRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AltCurrencyRates_AltCurrencyRate.Merge(m, src)
}
func (m *AltCurrencyRates_AltCurrencyRate) XXX_Size() int {
	return xxx_messageInfo_AltCurrencyRates_AltCurrencyRate.Size(m)
}
func (m *AltCurrencyRates_AltCurrencyRate) XXX_DiscardUnknown() {
	xxx_messageInfo_AltCurrencyRates_AltCurrencyRate.DiscardUnknown(m)
}

var xxx_messageInfo_AltCurrencyRates_AltCurrencyRate proto.InternalMessageInfo

func (m *AltCurrencyRates_AltCurrencyRate) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *AltCurrencyRates_AltCurrencyRate) GetCurrentRate() float32 {
	if m != nil {
		return m.CurrentRate
	}
	return 0
}

type GetMarketChartRequest struct {
	CurrencyCode         string   `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Days                 uint32   `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	StartTimestamp       int64    `protobuf:"varint,3,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp         int64    `protobuf:"varint,4,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMarketChartRequest) Reset()         { *m = GetMarketChartRequest{} }
func (m *GetMarketChartRequest) String() string { return proto.CompactTextString(m) }
func (*GetMarketChartRequest) ProtoMessage()    {}
func (*GetMarketChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{11}
}

func (m *GetMarketChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketChartRequest.Unmarshal(m, b)
}
func (m *GetMarketChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketChartRequest.Marshal(b, m, deterministic)
}
func (m *GetMarketChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketChartRequest.Merge(m, src)
}
func (m *GetMarketChartRequest) XXX_Size() int {
	return xxx_messageInfo_GetMarketChartRequest.Size(m)
}
func (m *GetMarketChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketChartRequest proto.InternalMessageInfo

func (m *GetMarketChartRequest) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *GetMarketChartRequest) GetDays() uint32 {
	if m != nil {
		return m.Days
	}
	return 0
}

func (m *GetMarketChartRequest) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

func (m *GetMarketChartRequest) GetEndTimestamp() int64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

type GetMarketChartResponse struct {
	Prices               []*GetMarketChartResponse_MarketChartDataPoint `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	Volumes              []*GetMarketChartResponse_MarketChartDataPoint `protobuf:"bytes,2,rep,name=volumes,proto3" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *GetMarketChartResponse) Reset()         { *m = GetMarketChartResponse{} }
func (m *GetMarketChartResponse) String() string { return proto.CompactTextString(m) }
func (*GetMarketChartResponse) ProtoMessage()    {}
func (*GetMarketChartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{12}
}

func (m *GetMarketChartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketChartResponse.Unmarshal(m, b)
}
func (m *GetMarketChartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketChartResponse.Marshal(b, m, deterministic)
}
func (m *GetMarketChartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketChartResponse.Merge(m, src)
}
func (m *GetMarketChartResponse) XXX_Size() int {
	return xxx_messageInfo_GetMarketChartResponse.Size(m)
}
func (m *GetMarketChartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketChartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketChartResponse proto.InternalMessageInfo

func (m *GetMarketChartResponse) GetPrices() []*GetMarketChartResponse_MarketChartDataPoint {
	if m != nil {
		return m.Prices
	}
	return nil
}

func (m *GetMarketChartResponse) GetVolumes() []*GetMarketChartResponse_MarketChartDataPoint {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type GetMarketChartResponse_MarketChartDataPoint struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value                float32  `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMarketChartResponse_MarketChartDataPoint) Reset() {
	*m = GetMarketChartResponse_MarketChartDataPoint{}
}
func (m *GetMarketChartResponse_MarketChartDataPoint) String() string {
	return proto.CompactTextString(m)
}
func (*GetMarketChartResponse_MarketChartDataPoint) ProtoMessage() {}
func (*GetMarketChartResponse_MarketChartDataPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{12, 0}
}

func (m *GetMarketChartResponse_MarketChartDataPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketChartResponse_MarketChartDataPoint.Unmarshal(m, b)
}
func (m *GetMarketChartResponse_MarketChartDataPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketChartResponse_MarketChartDataPoint.Marshal(b, m, deterministic)
}
func (m *GetMarketChartResponse_MarketChartDataPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketChartResponse_MarketChartDataPoint.Merge(m, src)
}
func (m *GetMarketChartResponse_MarketChartDataPoint) XXX_Size() int {
	return xxx_messageInfo_GetMarketChartResponse_MarketChartDataPoint.Size(m)
}
func (m *GetMarketChartResponse_MarketChartDataPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketChartResponse_MarketChartDataPoint.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketChartResponse_MarketChartDataPoint proto.InternalMessageInfo

func (m *GetMarketChartResponse_MarketChartDataPoint) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetMarketChartResponse_MarketChartDataPoint) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type StakingHistory struct {
	LastBlock            int64                                    `protobuf:"varint,1,opt,name=last_block,json=lastBlock,proto3" json:"last_block,omitempty"`
	LineItems            []*StakingHistory_StakingHistoryLineItem `protobuf:"bytes,2,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *StakingHistory) Reset()         { *m = StakingHistory{} }
func (m *StakingHistory) String() string { return proto.CompactTextString(m) }
func (*StakingHistory) ProtoMessage()    {}
func (*StakingHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{13}
}

func (m *StakingHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakingHistory.Unmarshal(m, b)
}
func (m *StakingHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakingHistory.Marshal(b, m, deterministic)
}
func (m *StakingHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakingHistory.Merge(m, src)
}
func (m *StakingHistory) XXX_Size() int {
	return xxx_messageInfo_StakingHistory.Size(m)
}
func (m *StakingHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_StakingHistory.DiscardUnknown(m)
}

var xxx_messageInfo_StakingHistory proto.InternalMessageInfo

func (m *StakingHistory) GetLastBlock() int64 {
	if m != nil {
		return m.LastBlock
	}
	return 0
}

func (m *StakingHistory) GetLineItems() []*StakingHistory_StakingHistoryLineItem {
	if m != nil {
		return m.LineItems
	}
	return nil
}

type StakingHistory_StakingHistoryLineItem struct {
	TxType               walletrpc.TransactionDetails_TransactionType `protobuf:"varint,1,opt,name=tx_type,json=txType,proto3,enum=walletrpc.TransactionDetails_TransactionType" json:"tx_type,omitempty"`
	RewardCredit         int64                                        `protobuf:"varint,2,opt,name=reward_credit,json=rewardCredit,proto3" json:"reward_credit,omitempty"`
	TicketCostCredit     int64                                        `protobuf:"varint,3,opt,name=ticket_cost_credit,json=ticketCostCredit,proto3" json:"ticket_cost_credit,omitempty"`
	TicketCostDebit      int64                                        `protobuf:"varint,4,opt,name=ticket_cost_debit,json=ticketCostDebit,proto3" json:"ticket_cost_debit,omitempty"`
	FeeDebit             int64                                        `protobuf:"varint,5,opt,name=fee_debit,json=feeDebit,proto3" json:"fee_debit,omitempty"`
	Timestamp            int64                                        `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TxHash               []byte                                       `protobuf:"bytes,7,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *StakingHistory_StakingHistoryLineItem) Reset()         { *m = StakingHistory_StakingHistoryLineItem{} }
func (m *StakingHistory_StakingHistoryLineItem) String() string { return proto.CompactTextString(m) }
func (*StakingHistory_StakingHistoryLineItem) ProtoMessage()    {}
func (*StakingHistory_StakingHistoryLineItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{13, 0}
}

func (m *StakingHistory_StakingHistoryLineItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakingHistory_StakingHistoryLineItem.Unmarshal(m, b)
}
func (m *StakingHistory_StakingHistoryLineItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakingHistory_StakingHistoryLineItem.Marshal(b, m, deterministic)
}
func (m *StakingHistory_StakingHistoryLineItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakingHistory_StakingHistoryLineItem.Merge(m, src)
}
func (m *StakingHistory_StakingHistoryLineItem) XXX_Size() int {
	return xxx_messageInfo_StakingHistory_StakingHistoryLineItem.Size(m)
}
func (m *StakingHistory_StakingHistoryLineItem) XXX_DiscardUnknown() {
	xxx_messageInfo_StakingHistory_StakingHistoryLineItem.DiscardUnknown(m)
}

var xxx_messageInfo_StakingHistory_StakingHistoryLineItem proto.InternalMessageInfo

func (m *StakingHistory_StakingHistoryLineItem) GetTxType() walletrpc.TransactionDetails_TransactionType {
	if m != nil {
		return m.TxType
	}
	return walletrpc.TransactionDetails_REGULAR
}

func (m *StakingHistory_StakingHistoryLineItem) GetRewardCredit() int64 {
	if m != nil {
		return m.RewardCredit
	}
	return 0
}

func (m *StakingHistory_StakingHistoryLineItem) GetTicketCostCredit() int64 {
	if m != nil {
		return m.TicketCostCredit
	}
	return 0
}

func (m *StakingHistory_StakingHistoryLineItem) GetTicketCostDebit() int64 {
	if m != nil {
		return m.TicketCostDebit
	}
	return 0
}

func (m *StakingHistory_StakingHistoryLineItem) GetFeeDebit() int64 {
	if m != nil {
		return m.FeeDebit
	}
	return 0
}

func (m *StakingHistory_StakingHistoryLineItem) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *StakingHistory_StakingHistoryLineItem) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

type StakeDiffHistory struct {
	SdiffValues          []float32 `protobuf:"fixed32,1,rep,packed,name=sdiff_values,json=sdiffValues,proto3" json:"sdiff_values,omitempty"`
	StartBlock           uint32    `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock             uint32    `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StakeDiffHistory) Reset()         { *m = StakeDiffHistory{} }
func (m *StakeDiffHistory) String() string { return proto.CompactTextString(m) }
func (*StakeDiffHistory) ProtoMessage()    {}
func (*StakeDiffHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{14}
}

func (m *StakeDiffHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeDiffHistory.Unmarshal(m, b)
}
func (m *StakeDiffHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeDiffHistory.Marshal(b, m, deterministic)
}
func (m *StakeDiffHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeDiffHistory.Merge(m, src)
}
func (m *StakeDiffHistory) XXX_Size() int {
	return xxx_messageInfo_StakeDiffHistory.Size(m)
}
func (m *StakeDiffHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeDiffHistory.DiscardUnknown(m)
}

var xxx_messageInfo_StakeDiffHistory proto.InternalMessageInfo

func (m *StakeDiffHistory) GetSdiffValues() []float32 {
	if m != nil {
		return m.SdiffValues
	}
	return nil
}

func (m *StakeDiffHistory) GetStartBlock() uint32 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *StakeDiffHistory) GetEndBlock() uint32 {
	if m != nil {
		return m.EndBlock
	}
	return 0
}

type UnspentOutput struct {
	TransactionHash      []byte   `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	OutputIndex          uint32   `protobuf:"varint,2,opt,name=output_index,json=outputIndex,proto3" json:"output_index,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PkScript             []byte   `protobuf:"bytes,4,opt,name=pk_script,json=pkScript,proto3" json:"pk_script,omitempty"`
	ReceiveTime          int64    `protobuf:"varint,5,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
	FromCoinbase         bool     `protobuf:"varint,6,opt,name=from_coinbase,json=fromCoinbase,proto3" json:"from_coinbase,omitempty"`
	Tree                 int32    `protobuf:"varint,7,opt,name=tree,proto3" json:"tree,omitempty"`
	AmountSum            int64    `protobuf:"varint,8,opt,name=amount_sum,json=amountSum,proto3" json:"amount_sum,omitempty"`
	ScriptClass          int32    `protobuf:"varint,9,opt,name=script_class,json=scriptClass,proto3" json:"script_class,omitempty"`
	Spendable            bool     `protobuf:"varint,10,opt,name=spendable,proto3" json:"spendable,omitempty"`
	Address              string   `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnspentOutput) Reset()         { *m = UnspentOutput{} }
func (m *UnspentOutput) String() string { return proto.CompactTextString(m) }
func (*UnspentOutput) ProtoMessage()    {}
func (*UnspentOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{15}
}

func (m *UnspentOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnspentOutput.Unmarshal(m, b)
}
func (m *UnspentOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnspentOutput.Marshal(b, m, deterministic)
}
func (m *UnspentOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnspentOutput.Merge(m, src)
}
func (m *UnspentOutput) XXX_Size() int {
	return xxx_messageInfo_UnspentOutput.Size(m)
}
func (m *UnspentOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_UnspentOutput.DiscardUnknown(m)
}

var xxx_messageInfo_UnspentOutput proto.InternalMessageInfo

func (m *UnspentOutput) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *UnspentOutput) GetOutputIndex() uint32 {
	if m != nil {
		return m.OutputIndex
	}
	return 0
}

func (m *UnspentOutput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *UnspentOutput) GetPkScript() []byte {
	if m != nil {
		return m.PkScript
	}
	return nil
}

func (m *UnspentOutput) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

func (m *UnspentOutput) GetFromCoinbase() bool {
	if m != nil {
		return m.FromCoinbase
	}
	return false
}

func (m *UnspentOutput) GetTree() int32 {
	if m != nil {
		return m.Tree
	}
	return 0
}

func (m *UnspentOutput) GetAmountSum() int64 {
	if m != nil {
		return m.AmountSum
	}
	return 0
}

func (m *UnspentOutput) GetScriptClass() int32 {
	if m != nil {
		return m.ScriptClass
	}
	return 0
}

func (m *UnspentOutput) GetSpendable() bool {
	if m != nil {
		return m.Spendable
	}
	return false
}

func (m *UnspentOutput) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateTransactionRequest struct {
	SourceOutputs         []*UnspentOutput `protobuf:"bytes,1,rep,name=source_outputs,json=sourceOutputs,proto3" json:"source_outputs,omitempty"`
	Amounts               map[string]int64 `protobuf:"bytes,2,rep,name=amounts,proto3" json:"amounts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	LockTime              int64            `protobuf:"varint,3,opt,name=lock_time,json=lockTime,proto3" json:"lock_time,omitempty"`
	Expiry                int64            `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	FeeRate               int32            `protobuf:"varint,5,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`
	SourceAccount         uint32           `protobuf:"varint,6,opt,name=source_account,json=sourceAccount,proto3" json:"source_account,omitempty"`
	ChangeAccount         uint32           `protobuf:"varint,7,opt,name=change_account,json=changeAccount,proto3" json:"change_account,omitempty"`
	RequiredConfirmations int32            `protobuf:"varint,8,opt,name=required_confirmations,json=requiredConfirmations,proto3" json:"required_confirmations,omitempty"`
	SendAllFlag           bool             `protobuf:"varint,9,opt,name=send_all_flag,json=sendAllFlag,proto3" json:"send_all_flag,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}         `json:"-"`
	XXX_unrecognized      []byte           `json:"-"`
	XXX_sizecache         int32            `json:"-"`
}

func (m *CreateTransactionRequest) Reset()         { *m = CreateTransactionRequest{} }
func (m *CreateTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTransactionRequest) ProtoMessage()    {}
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{16}
}

func (m *CreateTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTransactionRequest.Unmarshal(m, b)
}
func (m *CreateTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTransactionRequest.Marshal(b, m, deterministic)
}
func (m *CreateTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTransactionRequest.Merge(m, src)
}
func (m *CreateTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTransactionRequest.Size(m)
}
func (m *CreateTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTransactionRequest proto.InternalMessageInfo

func (m *CreateTransactionRequest) GetSourceOutputs() []*UnspentOutput {
	if m != nil {
		return m.SourceOutputs
	}
	return nil
}

func (m *CreateTransactionRequest) GetAmounts() map[string]int64 {
	if m != nil {
		return m.Amounts
	}
	return nil
}

func (m *CreateTransactionRequest) GetLockTime() int64 {
	if m != nil {
		return m.LockTime
	}
	return 0
}

func (m *CreateTransactionRequest) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *CreateTransactionRequest) GetFeeRate() int32 {
	if m != nil {
		return m.FeeRate
	}
	return 0
}

func (m *CreateTransactionRequest) GetSourceAccount() uint32 {
	if m != nil {
		return m.SourceAccount
	}
	return 0
}

func (m *CreateTransactionRequest) GetChangeAccount() uint32 {
	if m != nil {
		return m.ChangeAccount
	}
	return 0
}

func (m *CreateTransactionRequest) GetRequiredConfirmations() int32 {
	if m != nil {
		return m.RequiredConfirmations
	}
	return 0
}

func (m *CreateTransactionRequest) GetSendAllFlag() bool {
	if m != nil {
		return m.SendAllFlag
	}
	return false
}

type CreateTransactionResponse struct {
	UnsignedTransaction  []byte   `protobuf:"bytes,1,opt,name=unsigned_transaction,json=unsignedTransaction,proto3" json:"unsigned_transaction,omitempty"`
	EstimatedSignedSize  int32    `protobuf:"varint,2,opt,name=estimated_signed_size,json=estimatedSignedSize,proto3" json:"estimated_signed_size,omitempty"`
	EstimatedFee         int64    `protobuf:"varint,3,opt,name=estimated_fee,json=estimatedFee,proto3" json:"estimated_fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTransactionResponse) Reset()         { *m = CreateTransactionResponse{} }
func (m *CreateTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTransactionResponse) ProtoMessage()    {}
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16c1615ba816820, []int{17}
}

func (m *CreateTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTransactionResponse.Unmarshal(m, b)
}
func (m *CreateTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTransactionResponse.Marshal(b, m, deterministic)
}
func (m *CreateTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTransactionResponse.Merge(m, src)
}
func (m *CreateTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTransactionResponse.Size(m)
}
func (m *CreateTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTransactionResponse proto.InternalMessageInfo

func (m *CreateTransactionResponse) GetUnsignedTransaction() []byte {
	if m != nil {
		return m.UnsignedTransaction
	}
	return nil
}

func (m *CreateTransactionResponse) GetEstimatedSignedSize() int32 {
	if m != nil {
		return m.EstimatedSignedSize
	}
	return 0
}

func (m *CreateTransactionResponse) GetEstimatedFee() int64 {
	if m != nil {
		return m.EstimatedFee
	}
	return 0
}

func init() {
	proto.RegisterEnum("walletgui.Network", Network_name, Network_value)
	proto.RegisterEnum("walletgui.DisplayUnit", DisplayUnit_name, DisplayUnit_value)
	proto.RegisterEnum("walletgui.FiatCurrency", FiatCurrency_name, FiatCurrency_value)
	proto.RegisterEnum("walletgui.Theme", Theme_name, Theme_value)
	proto.RegisterEnum("walletgui.SetConfigResponse_UpdateStatus", SetConfigResponse_UpdateStatus_name, SetConfigResponse_UpdateStatus_value)
	proto.RegisterType((*GetConfigRequest)(nil), "walletgui.GetConfigRequest")
	proto.RegisterType((*SetConfigRequest)(nil), "walletgui.SetConfigRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "walletgui.SetConfigResponse")
	proto.RegisterType((*RPCEndpoint)(nil), "walletgui.RPCEndpoint")
	proto.RegisterType((*GRPCEndpoint)(nil), "walletgui.GRPCEndpoint")
	proto.RegisterType((*AppConfiguration)(nil), "walletgui.AppConfiguration")
	proto.RegisterMapType((map[string]*AppConfiguration_WalletPreferences)(nil), "walletgui.AppConfiguration.WalletPreferencesEntry")
	proto.RegisterType((*AppConfiguration_UIPreferences)(nil), "walletgui.AppConfiguration.UIPreferences")
	proto.RegisterType((*AppConfiguration_AccountPreference)(nil), "walletgui.AppConfiguration.AccountPreference")
	proto.RegisterType((*AppConfiguration_WalletPreferences)(nil), "walletgui.AppConfiguration.WalletPreferences")
	proto.RegisterMapType((map[uint32]*AppConfiguration_AccountPreference)(nil), "walletgui.AppConfiguration.WalletPreferences.AccountPrefsEntry")
	proto.RegisterType((*CheckConnectionRequest)(nil), "walletgui.CheckConnectionRequest")
	proto.RegisterType((*CheckConnectionResponse)(nil), "walletgui.CheckConnectionResponse")
	proto.RegisterType((*ConnectWalletRequest)(nil), "walletgui.ConnectWalletRequest")
	proto.RegisterType((*ConnectWalletResponse)(nil), "walletgui.ConnectWalletResponse")
	proto.RegisterType((*AltCurrencyRates)(nil), "walletgui.AltCurrencyRates")
	proto.RegisterType((*AltCurrencyRates_AltCurrencyRate)(nil), "walletgui.AltCurrencyRates.AltCurrencyRate")
	proto.RegisterType((*GetMarketChartRequest)(nil), "walletgui.GetMarketChartRequest")
	proto.RegisterType((*GetMarketChartResponse)(nil), "walletgui.GetMarketChartResponse")
	proto.RegisterType((*GetMarketChartResponse_MarketChartDataPoint)(nil), "walletgui.GetMarketChartResponse.MarketChartDataPoint")
	proto.RegisterType((*StakingHistory)(nil), "walletgui.StakingHistory")
	proto.RegisterType((*StakingHistory_StakingHistoryLineItem)(nil), "walletgui.StakingHistory.StakingHistoryLineItem")
	proto.RegisterType((*StakeDiffHistory)(nil), "walletgui.StakeDiffHistory")
	proto.RegisterType((*UnspentOutput)(nil), "walletgui.UnspentOutput")
	proto.RegisterType((*CreateTransactionRequest)(nil), "walletgui.CreateTransactionRequest")
	proto.RegisterMapType((map[string]int64)(nil), "walletgui.CreateTransactionRequest.AmountsEntry")
	proto.RegisterType((*CreateTransactionResponse)(nil), "walletgui.CreateTransactionResponse")
}

func init() {
	proto.RegisterFile("walletgui.proto", fileDescriptor_e16c1615ba816820)
}

var fileDescriptor_e16c1615ba816820 = []byte{
	// 2248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x4f, 0x73, 0x1b, 0x49,
	0x15, 0x8f, 0x24, 0xcb, 0x92, 0x9e, 0xfe, 0x78, 0xdc, 0x49, 0x1c, 0xad, 0x12, 0x36, 0xb6, 0xb2,
	0xbb, 0x24, 0xd9, 0x5d, 0x03, 0xde, 0x85, 0x62, 0xc3, 0x56, 0x6d, 0x39, 0xb2, 0x9d, 0x78, 0x77,
	0x1d, 0xa7, 0x5a, 0x32, 0x0b, 0x17, 0xa6, 0xda, 0x33, 0x2d, 0xab, 0xcb, 0xa3, 0x99, 0xa1, 0xbb,
	0x27, 0xb6, 0xf6, 0xc4, 0x89, 0x13, 0x17, 0x0e, 0x5c, 0xb9, 0xf2, 0x01, 0xa8, 0xa2, 0x8a, 0x0b,
	0x9f, 0x83, 0x03, 0x07, 0x2e, 0x54, 0xc1, 0x57, 0xe0, 0x44, 0xf5, 0x9f, 0x91, 0x5a, 0xb2, 0xe2,
	0xdd, 0x00, 0xb7, 0xe9, 0x5f, 0xbf, 0xff, 0xaf, 0xdf, 0xeb, 0xd7, 0x03, 0x6b, 0x17, 0x24, 0x8a,
	0xa8, 0x3c, 0xcb, 0xd8, 0x76, 0xca, 0x13, 0x99, 0xa0, 0xda, 0x14, 0xe8, 0xd4, 0x48, 0x6a, 0xd1,
	0xee, 0x0e, 0x78, 0xcf, 0xa8, 0xec, 0x25, 0xf1, 0x90, 0x9d, 0x61, 0xfa, 0xcb, 0x8c, 0x0a, 0x89,
	0xde, 0x06, 0x48, 0x89, 0x10, 0xe9, 0x88, 0x13, 0x41, 0xdb, 0x85, 0xcd, 0xc2, 0xc3, 0x06, 0x76,
	0x90, 0x6e, 0x0c, 0x5e, 0x7f, 0x91, 0xe7, 0x09, 0x00, 0x49, 0x53, 0x3f, 0xd0, 0xa0, 0xe6, 0xa9,
	0xef, 0xdc, 0xdd, 0x9e, 0xd9, 0xb0, 0x9b, 0xa6, 0x86, 0x21, 0xe3, 0x44, 0xb2, 0x24, 0xc6, 0x35,
	0x92, 0x23, 0x0b, 0xfa, 0x8a, 0x9b, 0x85, 0x87, 0xb5, 0x39, 0x7d, 0xff, 0x28, 0xc0, 0xba, 0xa3,
	0x50, 0xa4, 0x49, 0x2c, 0x28, 0x7a, 0x01, 0xcd, 0x2c, 0x0d, 0x89, 0xa4, 0xbe, 0x90, 0x44, 0x66,
	0x42, 0x2b, 0x6d, 0xed, 0x3c, 0x72, 0x94, 0x5e, 0x61, 0xda, 0x3e, 0xd1, 0x1c, 0x7d, 0xcd, 0x80,
	0x1b, 0x99, 0xb3, 0x42, 0xdf, 0x01, 0xa0, 0x9c, 0x27, 0xdc, 0x0f, 0x92, 0xd0, 0x58, 0x51, 0xc6,
	0x35, 0x8d, 0xf4, 0x92, 0x90, 0xa2, 0xf7, 0x61, 0xdd, 0x6c, 0x87, 0x54, 0x04, 0x9c, 0xa5, 0xca,
	0x89, 0x76, 0x49, 0xdb, 0xea, 0xe9, 0x8d, 0xbd, 0x19, 0xde, 0xfd, 0x18, 0x1a, 0xae, 0x26, 0x84,
	0xa0, 0xd5, 0x1f, 0xec, 0x0e, 0x4e, 0xfa, 0x7e, 0xff, 0xa4, 0xd7, 0xdb, 0xef, 0xf7, 0xbd, 0x1b,
	0xc8, 0x83, 0x86, 0xc5, 0xf6, 0x31, 0x3e, 0xc6, 0x5e, 0xa1, 0xfb, 0x9b, 0x22, 0xd4, 0xf1, 0xcb,
	0xde, 0x7e, 0x1c, 0xa6, 0x09, 0x8b, 0x25, 0x6a, 0x41, 0x91, 0x85, 0xda, 0xad, 0x1a, 0x2e, 0xb2,
	0x10, 0x75, 0xa0, 0x3a, 0x4a, 0x84, 0x8c, 0xc9, 0x38, 0x8f, 0xd2, 0x74, 0x8d, 0x10, 0xac, 0xa4,
	0x09, 0x97, 0xda, 0xa2, 0x26, 0xd6, 0xdf, 0x8a, 0x3e, 0x13, 0x94, 0x6b, 0xfa, 0x15, 0x43, 0x9f,
	0xaf, 0xd5, 0x9e, 0x8a, 0xf0, 0x45, 0xc2, 0xc3, 0x76, 0xd9, 0xec, 0xe5, 0x6b, 0xf4, 0x0e, 0xb4,
	0x02, 0xca, 0xa5, 0x3f, 0x64, 0x11, 0xf5, 0x35, 0xf7, 0xaa, 0xa6, 0x68, 0x28, 0xf4, 0x80, 0x45,
	0xf4, 0x85, 0x92, 0x70, 0x17, 0x6a, 0x9a, 0xea, 0x34, 0x4a, 0x4e, 0xdb, 0x15, 0x23, 0x42, 0x01,
	0x4f, 0xa3, 0xe4, 0x14, 0x7d, 0x00, 0x95, 0x98, 0xca, 0x8b, 0x84, 0x9f, 0xb7, 0xab, 0x3a, 0x2d,
	0xc8, 0x49, 0xcb, 0x0b, 0xb3, 0x83, 0x73, 0x12, 0x74, 0x0b, 0xca, 0x11, 0x39, 0xa5, 0x51, 0xbb,
	0xa6, 0xc5, 0x98, 0x45, 0xf7, 0x77, 0x25, 0x68, 0x3c, 0xfb, 0x7f, 0xc6, 0xe3, 0xaa, 0x5f, 0x2b,
	0xdf, 0xe4, 0x57, 0xf9, 0xf5, 0x7e, 0xad, 0xbe, 0x81, 0x5f, 0x15, 0xc7, 0x2f, 0xf4, 0x10, 0x3c,
	0x26, 0xfc, 0x0b, 0x22, 0x83, 0x11, 0x8b, 0xcf, 0xfc, 0x24, 0x8e, 0x26, 0x3a, 0x48, 0x55, 0xdc,
	0x62, 0xe2, 0x2b, 0x0b, 0x1f, 0xc7, 0xd1, 0x04, 0xbd, 0x0b, 0x2d, 0x12, 0x48, 0xf6, 0x8a, 0xfa,
	0xb9, 0xd2, 0x9a, 0x76, 0xa7, 0x69, 0x50, 0xab, 0x4f, 0x5b, 0x9c, 0xb0, 0xd8, 0x97, 0x93, 0x94,
	0xb6, 0x41, 0x53, 0x54, 0x15, 0x30, 0x98, 0xa4, 0x54, 0x69, 0x0b, 0x22, 0x46, 0x63, 0xe9, 0xcf,
	0xbc, 0xaa, 0x6b, 0x73, 0x5a, 0x06, 0xef, 0xe5, 0xbe, 0xbd, 0x07, 0x6b, 0x96, 0xf2, 0x9c, 0x4e,
	0x0c, 0x61, 0x43, 0x13, 0x36, 0x0d, 0xfc, 0x05, 0x9d, 0x28, 0xba, 0xee, 0xbf, 0x6a, 0xe0, 0x2d,
	0x96, 0x33, 0x7a, 0x0a, 0x9e, 0x09, 0x84, 0x4f, 0x6d, 0xba, 0x54, 0x41, 0x96, 0x1e, 0xd6, 0x77,
	0xee, 0x38, 0x11, 0x72, 0xd3, 0x89, 0x6d, 0x87, 0xca, 0xd7, 0x02, 0xfd, 0x04, 0x3a, 0x21, 0x1d,
	0x92, 0x2c, 0x92, 0xfe, 0x82, 0x2c, 0x9f, 0x85, 0x36, 0xc3, 0x77, 0x2c, 0xc5, 0x57, 0x73, 0xbc,
	0x87, 0x21, 0x22, 0x80, 0x2c, 0x53, 0xca, 0xe9, 0x90, 0x72, 0x1a, 0x07, 0x54, 0xb4, 0x4b, 0xda,
	0x84, 0x9d, 0x6b, 0x1a, 0xd1, 0xb6, 0x91, 0xf4, 0x72, 0xc6, 0xb4, 0x1f, 0x4b, 0x3e, 0xc1, 0xeb,
	0x17, 0x8b, 0x38, 0xfa, 0x18, 0x36, 0x48, 0x24, 0xfd, 0x90, 0x89, 0x34, 0x22, 0x13, 0x3f, 0xc8,
	0xb8, 0xda, 0x60, 0x54, 0xb4, 0x57, 0x36, 0x4b, 0x0f, 0x6b, 0xf8, 0x16, 0x89, 0xe4, 0x9e, 0xd9,
	0xec, 0x4d, 0xf7, 0xd0, 0x4b, 0x68, 0x65, 0x6c, 0xce, 0xa8, 0xb2, 0xee, 0x8e, 0x8f, 0xae, 0x33,
	0xea, 0xe4, 0xd0, 0x51, 0x8c, 0x9b, 0x19, 0x73, 0x96, 0x9d, 0xbf, 0x17, 0xa0, 0x39, 0x47, 0x80,
	0x3e, 0x81, 0x46, 0x6e, 0x55, 0x16, 0x33, 0x69, 0x5b, 0xe1, 0x86, 0xa3, 0xc1, 0xda, 0x75, 0x12,
	0x33, 0x89, 0xeb, 0xe1, 0x6c, 0x81, 0x3e, 0x85, 0xe6, 0x90, 0x11, 0x99, 0x7b, 0x33, 0xd1, 0x71,
	0x6e, 0xcd, 0x65, 0xed, 0x80, 0x11, 0x69, 0x1d, 0x9a, 0xe0, 0xc6, 0xd0, 0x59, 0xa1, 0x6d, 0xb8,
	0xc9, 0x84, 0xed, 0xfa, 0x3e, 0x8d, 0x03, 0x3e, 0x49, 0x25, 0x0d, 0x75, 0xd5, 0x55, 0xf1, 0x3a,
	0x13, 0xc6, 0xab, 0xfd, 0x7c, 0x03, 0xbd, 0x07, 0x65, 0x39, 0xa2, 0xb6, 0xf2, 0x5a, 0x3b, 0x9e,
	0xa3, 0x65, 0xa0, 0x70, 0x6c, 0xb6, 0x3b, 0x27, 0xb0, 0xbe, 0x1b, 0x04, 0x49, 0x16, 0x3b, 0x09,
	0x50, 0xe7, 0x9c, 0x09, 0x7f, 0xc4, 0xc2, 0x90, 0xc6, 0xda, 0xc5, 0x2a, 0xae, 0x32, 0xf1, 0x5c,
	0xaf, 0xd1, 0x03, 0x68, 0xe6, 0x21, 0x48, 0x78, 0x48, 0xb9, 0xf6, 0xa3, 0x89, 0xf3, 0xb8, 0x1c,
	0x2b, 0xac, 0xf3, 0xe7, 0x12, 0xac, 0x5f, 0xc9, 0x37, 0x0a, 0xa1, 0x49, 0x8c, 0x32, 0x9d, 0xa6,
	0xfc, 0xe0, 0x7e, 0xf6, 0x46, 0xa7, 0x66, 0xdb, 0xb1, 0xd7, 0x1e, 0xa1, 0x06, 0x71, 0x20, 0x34,
	0x84, 0xb7, 0x73, 0x2d, 0x63, 0x76, 0x49, 0xb9, 0xcf, 0xcd, 0xd5, 0xe9, 0xdb, 0x13, 0x2d, 0xb4,
	0xc5, 0xf5, 0x9d, 0x2d, 0xab, 0x96, 0xa7, 0xc1, 0x36, 0xce, 0x62, 0x2b, 0xf6, 0x48, 0xb1, 0xd8,
	0xcb, 0x16, 0xdf, 0x25, 0x57, 0xc1, 0x3d, 0x2b, 0x05, 0x0d, 0xe1, 0x3e, 0xcf, 0x62, 0x9f, 0x64,
	0x32, 0xf1, 0x4f, 0xb3, 0xc9, 0x32, 0x45, 0x25, 0xad, 0x68, 0x73, 0x5e, 0xd1, 0x80, 0x05, 0xe7,
	0x54, 0x3e, 0x55, 0x1c, 0x53, 0x3d, 0x3c, 0x8b, 0x77, 0x33, 0x99, 0xb8, 0x60, 0xae, 0xa7, 0x13,
	0xcf, 0xa5, 0xc8, 0xb8, 0x8c, 0x3c, 0x28, 0x9d, 0xd3, 0x89, 0x4e, 0x4e, 0x13, 0xab, 0x4f, 0xd4,
	0x83, 0xf2, 0x2b, 0x12, 0x65, 0xd4, 0x7a, 0xf7, 0xe1, 0x75, 0x41, 0xbd, 0x92, 0x72, 0x6c, 0x78,
	0x9f, 0x14, 0x7f, 0x5c, 0xe8, 0x08, 0xd8, 0x58, 0x5e, 0xaa, 0xae, 0xd2, 0xda, 0x9b, 0x2b, 0xbd,
	0x22, 0xd4, 0x51, 0xda, 0xfd, 0x6d, 0x01, 0x36, 0x7a, 0x23, 0x1a, 0x9c, 0xf7, 0x92, 0x38, 0xa6,
	0x81, 0x9e, 0x5c, 0xec, 0xc4, 0xf3, 0x29, 0x34, 0xcf, 0x78, 0x1a, 0x4c, 0x7b, 0x94, 0x1d, 0x7a,
	0x5e, 0xdb, 0xee, 0x1a, 0x8a, 0x7a, 0x7a, 0x97, 0x7d, 0x02, 0x8d, 0x39, 0x66, 0x63, 0xa8, 0x5b,
	0xb1, 0x2e, 0x6f, 0xdd, 0x61, 0xed, 0x1e, 0xc1, 0x9d, 0x2b, 0x26, 0xd9, 0x99, 0xe8, 0x9e, 0xaa,
	0x90, 0x7e, 0x16, 0x04, 0x54, 0x08, 0x5b, 0x21, 0x33, 0x40, 0x5d, 0x47, 0x7a, 0x52, 0xb1, 0xad,
	0xd4, 0x2c, 0xba, 0x7b, 0x70, 0xcb, 0x4a, 0x32, 0x91, 0xc8, 0xfd, 0xfb, 0x60, 0xda, 0x50, 0xdd,
	0x2e, 0x6c, 0x82, 0xec, 0x5d, 0x2c, 0xb4, 0xdf, 0xee, 0xaf, 0x0a, 0x70, 0x7b, 0x41, 0xcc, 0x7f,
	0x6f, 0x13, 0xfa, 0x08, 0xaa, 0xd3, 0xc8, 0x94, 0xae, 0x0f, 0xeb, 0x94, 0xb0, 0xfb, 0xd7, 0x02,
	0x78, 0xbb, 0xd1, 0xac, 0x53, 0x11, 0x49, 0x05, 0xda, 0x85, 0x32, 0x57, 0x1f, 0xb6, 0xa6, 0xdf,
	0x77, 0x4f, 0xc2, 0x02, 0xed, 0x22, 0x80, 0x0d, 0xa7, 0xba, 0x17, 0x23, 0x22, 0xa4, 0x6f, 0xa6,
	0xc5, 0xd0, 0xb7, 0x95, 0x5a, 0xc2, 0x4d, 0x05, 0x9b, 0x39, 0x2f, 0x1c, 0x88, 0xce, 0xcf, 0x61,
	0x6d, 0x41, 0x82, 0x6a, 0x4a, 0x79, 0x5f, 0x35, 0x63, 0x65, 0xc1, 0x0e, 0x1c, 0x16, 0xd4, 0x93,
	0xe5, 0x16, 0xd8, 0xb5, 0xf4, 0x95, 0x42, 0x2d, 0xbc, 0x88, 0xeb, 0x16, 0x53, 0x72, 0xba, 0xbf,
	0x2f, 0xc0, 0xed, 0x67, 0x54, 0x1e, 0x11, 0x7e, 0x4e, 0x65, 0x6f, 0x44, 0xf8, 0x34, 0x4b, 0xdf,
	0x4a, 0x03, 0x82, 0x95, 0x90, 0x4c, 0x84, 0x6d, 0x89, 0xfa, 0x1b, 0x7d, 0x17, 0xd6, 0x84, 0x24,
	0x5c, 0xfa, 0x92, 0x8d, 0xa9, 0x90, 0x64, 0x9c, 0xea, 0x48, 0x97, 0x70, 0x4b, 0xc3, 0x83, 0x1c,
	0x55, 0x1a, 0x68, 0x1c, 0x3a, 0x64, 0x2b, 0x9a, 0xac, 0x41, 0xe3, 0x70, 0x4a, 0xd4, 0xfd, 0x75,
	0x11, 0x36, 0x16, 0x0d, 0x9c, 0xce, 0xe9, 0xab, 0x29, 0x67, 0xc1, 0x34, 0x05, 0x3f, 0x72, 0x33,
	0xb9, 0x94, 0x65, 0xdb, 0xc1, 0xf6, 0x88, 0x24, 0x2f, 0x75, 0xa2, 0xad, 0x14, 0xf4, 0x12, 0x2a,
	0xaf, 0x92, 0x28, 0x1b, 0x53, 0xe5, 0xcf, 0xff, 0x22, 0x30, 0x17, 0xd3, 0xf9, 0x1c, 0x6e, 0x2d,
	0x23, 0x50, 0x27, 0x77, 0xe6, 0x75, 0x41, 0x7b, 0x3d, 0x03, 0xd4, 0xc9, 0x9d, 0xf5, 0x98, 0xa2,
	0x6d, 0x1a, 0xdd, 0x3f, 0x95, 0xa0, 0xd5, 0x97, 0xe4, 0x9c, 0xc5, 0x67, 0xcf, 0x99, 0x90, 0x09,
	0x9f, 0xa8, 0x87, 0x85, 0x3e, 0x3f, 0xa7, 0x51, 0x12, 0x9c, 0xe7, 0x72, 0x14, 0xf2, 0x54, 0x01,
	0xe8, 0x18, 0x20, 0x62, 0x31, 0xf5, 0x99, 0xa4, 0xe3, 0xdc, 0xa5, 0xef, 0xbb, 0x8f, 0x98, 0x39,
	0x69, 0x0b, 0xcb, 0x2f, 0x59, 0x4c, 0x0f, 0x25, 0x1d, 0xe3, 0x5a, 0x64, 0xbf, 0x44, 0xe7, 0x8f,
	0x45, 0xd8, 0x58, 0x4e, 0x85, 0x0e, 0xa0, 0x22, 0x2f, 0xcd, 0x9c, 0x68, 0x46, 0x84, 0x0f, 0x9d,
	0x3b, 0x60, 0xc0, 0x49, 0x2c, 0x88, 0x6e, 0x28, 0x7b, 0x54, 0x12, 0x16, 0x09, 0x17, 0x52, 0xc3,
	0x24, 0x5e, 0x95, 0x97, 0x7a, 0xa8, 0x7c, 0x00, 0x4d, 0x4e, 0x2f, 0x08, 0x0f, 0xfd, 0x80, 0xd3,
	0x90, 0x49, 0x5b, 0x10, 0x0d, 0x03, 0xf6, 0x34, 0xa6, 0x1a, 0x88, 0xd4, 0x77, 0x8a, 0x1f, 0x24,
	0x42, 0xe6, 0x94, 0xe6, 0x90, 0x79, 0x66, 0xa7, 0x97, 0x08, 0x69, 0xa9, 0x1f, 0xc3, 0xba, 0x4b,
	0x1d, 0xd2, 0x53, 0x26, 0xed, 0x51, 0x5b, 0x9b, 0x11, 0xef, 0x29, 0x58, 0x0d, 0x02, 0x43, 0x4a,
	0x2d, 0x4d, 0x59, 0xd3, 0x54, 0x87, 0x94, 0x9a, 0xcd, 0xb9, 0xac, 0xad, 0x2e, 0x66, 0xed, 0x8e,
	0x8e, 0xc0, 0x88, 0x88, 0x91, 0x1e, 0xca, 0x1b, 0xca, 0xa5, 0xe7, 0x44, 0x8c, 0xba, 0x02, 0x3c,
	0x15, 0x34, 0xba, 0xc7, 0x86, 0xc3, 0x3c, 0x73, 0x5b, 0xd0, 0x10, 0x21, 0x1b, 0x0e, 0x7d, 0x9d,
	0x5b, 0x73, 0x80, 0x8b, 0xb8, 0xae, 0xb1, 0x9f, 0x6a, 0x08, 0xdd, 0x87, 0xba, 0x29, 0x23, 0x93,
	0x5d, 0x53, 0x61, 0xa0, 0x21, 0x93, 0xde, 0xbb, 0x50, 0x53, 0xe5, 0x63, 0xb6, 0xcd, 0x6b, 0x44,
	0xb5, 0x2c, 0xbd, 0xd9, 0xfd, 0x67, 0x11, 0x9a, 0x27, 0xb1, 0x48, 0x69, 0x2c, 0x8f, 0x33, 0x99,
	0x66, 0x12, 0x3d, 0x02, 0x4f, 0xce, 0x82, 0x6e, 0x0c, 0x35, 0x2f, 0xf0, 0x35, 0x07, 0x57, 0x16,
	0x2b, 0xeb, 0x12, 0xcd, 0xe4, 0xb3, 0x38, 0xa4, 0x97, 0x56, 0x77, 0xdd, 0x60, 0x87, 0x0a, 0x42,
	0x1b, 0xb0, 0x4a, 0xc6, 0xea, 0x4a, 0xb5, 0x61, 0xb7, 0x2b, 0x65, 0x54, 0x7a, 0xee, 0x9b, 0xf7,
	0xaa, 0x0e, 0x72, 0x03, 0x57, 0xd3, 0xf3, 0xbe, 0x5e, 0x2b, 0xb9, 0x9c, 0x06, 0x54, 0x3d, 0x3b,
	0x54, 0xdc, 0x6c, 0x80, 0xeb, 0x16, 0x53, 0x35, 0xaf, 0xf2, 0x3f, 0xe4, 0xc9, 0xd8, 0x57, 0xaf,
	0x8c, 0x53, 0xf5, 0x68, 0x5f, 0xd5, 0x7d, 0xbd, 0xa1, 0xc0, 0x9e, 0xc5, 0x54, 0xd7, 0x91, 0x9c,
	0x52, 0x1d, 0xe7, 0x32, 0xd6, 0xdf, 0xaa, 0x16, 0x8c, 0x09, 0xbe, 0xc8, 0xc6, 0xfa, 0xd5, 0x53,
	0xc2, 0x35, 0x83, 0xf4, 0xb3, 0xb1, 0x0e, 0xb8, 0x36, 0xc2, 0x0f, 0x22, 0x22, 0x84, 0x7e, 0xee,
	0x94, 0x71, 0xdd, 0x60, 0x3d, 0x05, 0xa9, 0xf4, 0xaa, 0x78, 0x85, 0xe4, 0x34, 0x32, 0x8f, 0x9d,
	0x2a, 0x9e, 0x01, 0xa8, 0x0d, 0x15, 0x12, 0x86, 0x5c, 0x5d, 0x35, 0xe6, 0x91, 0x93, 0x2f, 0xbb,
	0x7f, 0x2b, 0x41, 0xbb, 0xc7, 0x29, 0x91, 0xd4, 0x39, 0xd4, 0x79, 0x17, 0xfd, 0x0c, 0x5a, 0x22,
	0xc9, 0x78, 0x40, 0x7d, 0x13, 0xbd, 0xbc, 0x57, 0xb5, 0x9d, 0x3a, 0x9c, 0xcb, 0x13, 0x6e, 0x1a,
	0x7a, 0xb3, 0x12, 0xe8, 0x73, 0xa8, 0x18, 0x2f, 0x96, 0x55, 0xf0, 0xeb, 0xd4, 0x6e, 0xef, 0x1a,
	0x16, 0x33, 0x2d, 0xe6, 0x02, 0x54, 0x72, 0xd4, 0xe1, 0x30, 0xc1, 0x37, 0x79, 0xab, 0x2a, 0x40,
	0x47, 0x7e, 0x03, 0x56, 0xe9, 0x65, 0xca, 0xf8, 0xc4, 0xd6, 0x86, 0x5d, 0xa1, 0xb7, 0x40, 0x55,
	0x80, 0xb9, 0x40, 0xca, 0x3a, 0x6a, 0x95, 0x21, 0xa5, 0xfa, 0x12, 0x7a, 0x77, 0xea, 0x9c, 0x1d,
	0x1b, 0x75, 0xb6, 0x9a, 0xb9, 0x0b, 0x76, 0xe8, 0x52, 0x64, 0xc1, 0x88, 0xc4, 0x67, 0x33, 0xb2,
	0x8a, 0x21, 0x33, 0x68, 0x4e, 0xf6, 0x43, 0xd8, 0x50, 0xf3, 0x24, 0xe3, 0x34, 0x34, 0x73, 0x3f,
	0x1f, 0xeb, 0x39, 0x4a, 0xe8, 0x6c, 0x96, 0xf1, 0xed, 0x7c, 0xb7, 0xe7, 0x6e, 0xa2, 0x2e, 0x34,
	0x85, 0xaa, 0x03, 0x12, 0x45, 0xfe, 0x30, 0x22, 0x67, 0x3a, 0xb5, 0x55, 0x5c, 0x57, 0xe0, 0x6e,
	0x14, 0x1d, 0x44, 0xe4, 0xac, 0xf3, 0x04, 0x1a, 0x6e, 0x44, 0x96, 0xcc, 0x75, 0x73, 0x3d, 0xb7,
	0xe4, 0x0e, 0x6a, 0x7f, 0x28, 0xc0, 0x5b, 0x4b, 0xe2, 0x6c, 0xef, 0xa0, 0x1f, 0xc0, 0xad, 0x2c,
	0x16, 0xec, 0x2c, 0x56, 0xd7, 0xf7, 0x6c, 0xdf, 0x56, 0xd6, 0xcd, 0x7c, 0xcf, 0x61, 0x45, 0x3b,
	0x70, 0x9b, 0x0a, 0xc9, 0xc6, 0xfa, 0xca, 0xb7, 0xac, 0x82, 0x7d, 0x9d, 0xff, 0x19, 0xba, 0x39,
	0xdd, 0xec, 0xeb, 0xbd, 0x3e, 0xfb, 0x5a, 0x97, 0xc5, 0x8c, 0x67, 0x48, 0xf3, 0xec, 0x35, 0xa6,
	0xe0, 0x01, 0xa5, 0x8f, 0xbf, 0x07, 0x95, 0xfc, 0xe1, 0x5e, 0x87, 0xca, 0xd1, 0xee, 0xe1, 0x8b,
	0x17, 0xfb, 0x03, 0xef, 0x86, 0x5a, 0x0c, 0xf6, 0xfb, 0x03, 0xb5, 0x28, 0x20, 0x80, 0xd5, 0xfe,
	0xe1, 0x91, 0xfa, 0x2e, 0x3e, 0xde, 0x82, 0xba, 0xf3, 0x7a, 0x43, 0x15, 0x28, 0xed, 0xf5, 0xb0,
	0x77, 0x03, 0xd5, 0xa0, 0xbc, 0x3b, 0x38, 0x3e, 0xea, 0x7b, 0x85, 0xc7, 0x9b, 0xd0, 0x70, 0x1f,
	0x69, 0x8a, 0xe6, 0xa4, 0xbf, 0xe7, 0xdd, 0x50, 0x1f, 0xfb, 0x27, 0xd8, 0x2b, 0x3c, 0xbe, 0x07,
	0x65, 0xfd, 0xc0, 0x52, 0x5c, 0x5f, 0x1e, 0x3e, 0x7b, 0xae, 0x34, 0x56, 0x61, 0x65, 0x6f, 0x17,
	0x7f, 0xe1, 0x15, 0x76, 0xfe, 0x5d, 0x80, 0xda, 0x74, 0x30, 0x46, 0xfb, 0x50, 0x9b, 0xfe, 0x13,
	0x44, 0x77, 0xe7, 0x6f, 0xd7, 0xb9, 0xbf, 0x7e, 0x9d, 0xeb, 0xfe, 0xf0, 0xa1, 0x03, 0xa8, 0xf5,
	0x97, 0x8a, 0x59, 0xfc, 0x79, 0xd8, 0xb9, 0x77, 0xdd, 0x3f, 0x3b, 0xf4, 0x0b, 0x58, 0xbf, 0x92,
	0x59, 0xf4, 0xe0, 0x5b, 0xd4, 0x57, 0xe7, 0x9d, 0xeb, 0x89, 0x8c, 0xfc, 0x9d, 0xbf, 0x14, 0xa0,
	0x65, 0x33, 0xd2, 0xa7, 0xfc, 0x15, 0x0b, 0x28, 0xfa, 0x19, 0xac, 0x2d, 0x8c, 0xd8, 0x68, 0xcb,
	0x95, 0xb5, 0xf4, 0x45, 0xd0, 0xe9, 0x5e, 0x47, 0x62, 0x9d, 0xc1, 0xd0, 0x9c, 0x1b, 0x93, 0xd1,
	0x7d, 0x97, 0x69, 0xc9, 0x1c, 0xde, 0xd9, 0x7c, 0x3d, 0x81, 0x75, 0x60, 0x08, 0xcd, 0xfd, 0x4b,
	0x53, 0xa5, 0x66, 0xe8, 0x3d, 0x81, 0xd6, 0xfc, 0x20, 0x84, 0x36, 0xaf, 0x99, 0x91, 0x8c, 0x9a,
	0xad, 0x6f, 0x9c, 0xa2, 0x4e, 0x57, 0xf5, 0x2f, 0xe3, 0x8f, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0x7f, 0x27, 0x43, 0x5b, 0x16, 0x00, 0x00,
}
