// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dcrwalletgui.proto

package dcrwalletgui

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Network int32

const (
	Network_MAINNET Network = 0
	Network_TESTNET Network = 1
	Network_SIMNET  Network = 2
)

var Network_name = map[int32]string{
	0: "MAINNET",
	1: "TESTNET",
	2: "SIMNET",
}

var Network_value = map[string]int32{
	"MAINNET": 0,
	"TESTNET": 1,
	"SIMNET":  2,
}

func (x Network) String() string {
	return proto.EnumName(Network_name, int32(x))
}

func (Network) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{0}
}

type SetConfigResponse_UpdateStatus int32

const (
	SetConfigResponse_STATUS_SUCCESS SetConfigResponse_UpdateStatus = 0
	SetConfigResponse_STATUS_ERROR   SetConfigResponse_UpdateStatus = 1
)

var SetConfigResponse_UpdateStatus_name = map[int32]string{
	0: "STATUS_SUCCESS",
	1: "STATUS_ERROR",
}

var SetConfigResponse_UpdateStatus_value = map[string]int32{
	"STATUS_SUCCESS": 0,
	"STATUS_ERROR":   1,
}

func (x SetConfigResponse_UpdateStatus) String() string {
	return proto.EnumName(SetConfigResponse_UpdateStatus_name, int32(x))
}

func (SetConfigResponse_UpdateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{2, 0}
}

type GetConfigRequest struct {
	Passphrase           []byte   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{0}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

type SetConfigRequest struct {
	AppConfig            *AppConfiguration `protobuf:"bytes,1,opt,name=app_config,json=appConfig,proto3" json:"app_config,omitempty"`
	Passphrase           []byte            `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{1}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetAppConfig() *AppConfiguration {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

func (m *SetConfigRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

type SetConfigResponse struct {
	UpdateStatus         SetConfigResponse_UpdateStatus `protobuf:"varint,1,opt,name=update_status,json=updateStatus,proto3,enum=dcrwalletgui.SetConfigResponse_UpdateStatus" json:"update_status,omitempty"`
	ErrorCode            int32                          `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorDescription     string                         `protobuf:"bytes,3,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SetConfigResponse) Reset()         { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()    {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{2}
}

func (m *SetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigResponse.Unmarshal(m, b)
}
func (m *SetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigResponse.Merge(m, src)
}
func (m *SetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigResponse.Size(m)
}
func (m *SetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigResponse proto.InternalMessageInfo

func (m *SetConfigResponse) GetUpdateStatus() SetConfigResponse_UpdateStatus {
	if m != nil {
		return m.UpdateStatus
	}
	return SetConfigResponse_STATUS_SUCCESS
}

func (m *SetConfigResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *SetConfigResponse) GetErrorDescription() string {
	if m != nil {
		return m.ErrorDescription
	}
	return ""
}

type RPCEndpoint struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	CertFileName         string   `protobuf:"bytes,6,opt,name=cert_file_name,json=certFileName,proto3" json:"cert_file_name,omitempty"`
	CertBlob             string   `protobuf:"bytes,7,opt,name=cert_blob,json=certBlob,proto3" json:"cert_blob,omitempty"`
	Network              Network  `protobuf:"varint,8,opt,name=network,proto3,enum=dcrwalletgui.Network" json:"network,omitempty"`
	Label                string   `protobuf:"bytes,9,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCEndpoint) Reset()         { *m = RPCEndpoint{} }
func (m *RPCEndpoint) String() string { return proto.CompactTextString(m) }
func (*RPCEndpoint) ProtoMessage()    {}
func (*RPCEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{3}
}

func (m *RPCEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCEndpoint.Unmarshal(m, b)
}
func (m *RPCEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCEndpoint.Marshal(b, m, deterministic)
}
func (m *RPCEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCEndpoint.Merge(m, src)
}
func (m *RPCEndpoint) XXX_Size() int {
	return xxx_messageInfo_RPCEndpoint.Size(m)
}
func (m *RPCEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_RPCEndpoint proto.InternalMessageInfo

func (m *RPCEndpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RPCEndpoint) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RPCEndpoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RPCEndpoint) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RPCEndpoint) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RPCEndpoint) GetCertFileName() string {
	if m != nil {
		return m.CertFileName
	}
	return ""
}

func (m *RPCEndpoint) GetCertBlob() string {
	if m != nil {
		return m.CertBlob
	}
	return ""
}

func (m *RPCEndpoint) GetNetwork() Network {
	if m != nil {
		return m.Network
	}
	return Network_MAINNET
}

func (m *RPCEndpoint) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type GRPCEndpoint struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	CertFileName         string   `protobuf:"bytes,4,opt,name=cert_file_name,json=certFileName,proto3" json:"cert_file_name,omitempty"`
	CertBlob             string   `protobuf:"bytes,5,opt,name=cert_blob,json=certBlob,proto3" json:"cert_blob,omitempty"`
	Network              Network  `protobuf:"varint,6,opt,name=network,proto3,enum=dcrwalletgui.Network" json:"network,omitempty"`
	Label                string   `protobuf:"bytes,7,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GRPCEndpoint) Reset()         { *m = GRPCEndpoint{} }
func (m *GRPCEndpoint) String() string { return proto.CompactTextString(m) }
func (*GRPCEndpoint) ProtoMessage()    {}
func (*GRPCEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{4}
}

func (m *GRPCEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GRPCEndpoint.Unmarshal(m, b)
}
func (m *GRPCEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GRPCEndpoint.Marshal(b, m, deterministic)
}
func (m *GRPCEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GRPCEndpoint.Merge(m, src)
}
func (m *GRPCEndpoint) XXX_Size() int {
	return xxx_messageInfo_GRPCEndpoint.Size(m)
}
func (m *GRPCEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_GRPCEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_GRPCEndpoint proto.InternalMessageInfo

func (m *GRPCEndpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GRPCEndpoint) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *GRPCEndpoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GRPCEndpoint) GetCertFileName() string {
	if m != nil {
		return m.CertFileName
	}
	return ""
}

func (m *GRPCEndpoint) GetCertBlob() string {
	if m != nil {
		return m.CertBlob
	}
	return ""
}

func (m *GRPCEndpoint) GetNetwork() Network {
	if m != nil {
		return m.Network
	}
	return Network_MAINNET
}

func (m *GRPCEndpoint) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type AccountPreference struct {
	AccountNumber        uint32   `protobuf:"varint,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	IsHidden             bool     `protobuf:"varint,2,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	DisplayOrder         uint32   `protobuf:"varint,3,opt,name=displayOrder,proto3" json:"displayOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountPreference) Reset()         { *m = AccountPreference{} }
func (m *AccountPreference) String() string { return proto.CompactTextString(m) }
func (*AccountPreference) ProtoMessage()    {}
func (*AccountPreference) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{5}
}

func (m *AccountPreference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPreference.Unmarshal(m, b)
}
func (m *AccountPreference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPreference.Marshal(b, m, deterministic)
}
func (m *AccountPreference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPreference.Merge(m, src)
}
func (m *AccountPreference) XXX_Size() int {
	return xxx_messageInfo_AccountPreference.Size(m)
}
func (m *AccountPreference) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPreference.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPreference proto.InternalMessageInfo

func (m *AccountPreference) GetAccountNumber() uint32 {
	if m != nil {
		return m.AccountNumber
	}
	return 0
}

func (m *AccountPreference) GetIsHidden() bool {
	if m != nil {
		return m.IsHidden
	}
	return false
}

func (m *AccountPreference) GetDisplayOrder() uint32 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

type WalletPreferences struct {
	WalletEndpointId     string               `protobuf:"bytes,1,opt,name=wallet_endpoint_id,json=walletEndpointId,proto3" json:"wallet_endpoint_id,omitempty"`
	AccountPrefs         []*AccountPreference `protobuf:"bytes,2,rep,name=account_prefs,json=accountPrefs,proto3" json:"account_prefs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WalletPreferences) Reset()         { *m = WalletPreferences{} }
func (m *WalletPreferences) String() string { return proto.CompactTextString(m) }
func (*WalletPreferences) ProtoMessage()    {}
func (*WalletPreferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{6}
}

func (m *WalletPreferences) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletPreferences.Unmarshal(m, b)
}
func (m *WalletPreferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletPreferences.Marshal(b, m, deterministic)
}
func (m *WalletPreferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletPreferences.Merge(m, src)
}
func (m *WalletPreferences) XXX_Size() int {
	return xxx_messageInfo_WalletPreferences.Size(m)
}
func (m *WalletPreferences) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletPreferences.DiscardUnknown(m)
}

var xxx_messageInfo_WalletPreferences proto.InternalMessageInfo

func (m *WalletPreferences) GetWalletEndpointId() string {
	if m != nil {
		return m.WalletEndpointId
	}
	return ""
}

func (m *WalletPreferences) GetAccountPrefs() []*AccountPreference {
	if m != nil {
		return m.AccountPrefs
	}
	return nil
}

type AppConfiguration struct {
	DcrdEndpoint            *RPCEndpoint         `protobuf:"bytes,1,opt,name=dcrd_endpoint,json=dcrdEndpoint,proto3" json:"dcrd_endpoint,omitempty"`
	WalletEndpoints         []*GRPCEndpoint      `protobuf:"bytes,2,rep,name=wallet_endpoints,json=walletEndpoints,proto3" json:"wallet_endpoints,omitempty"`
	DefaultWalletEndpointId string               `protobuf:"bytes,3,opt,name=default_wallet_endpoint_id,json=defaultWalletEndpointId,proto3" json:"default_wallet_endpoint_id,omitempty"`
	WalletPreferences       []*WalletPreferences `protobuf:"bytes,4,rep,name=wallet_preferences,json=walletPreferences,proto3" json:"wallet_preferences,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}             `json:"-"`
	XXX_unrecognized        []byte               `json:"-"`
	XXX_sizecache           int32                `json:"-"`
}

func (m *AppConfiguration) Reset()         { *m = AppConfiguration{} }
func (m *AppConfiguration) String() string { return proto.CompactTextString(m) }
func (*AppConfiguration) ProtoMessage()    {}
func (*AppConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{7}
}

func (m *AppConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfiguration.Unmarshal(m, b)
}
func (m *AppConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfiguration.Marshal(b, m, deterministic)
}
func (m *AppConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfiguration.Merge(m, src)
}
func (m *AppConfiguration) XXX_Size() int {
	return xxx_messageInfo_AppConfiguration.Size(m)
}
func (m *AppConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfiguration proto.InternalMessageInfo

func (m *AppConfiguration) GetDcrdEndpoint() *RPCEndpoint {
	if m != nil {
		return m.DcrdEndpoint
	}
	return nil
}

func (m *AppConfiguration) GetWalletEndpoints() []*GRPCEndpoint {
	if m != nil {
		return m.WalletEndpoints
	}
	return nil
}

func (m *AppConfiguration) GetDefaultWalletEndpointId() string {
	if m != nil {
		return m.DefaultWalletEndpointId
	}
	return ""
}

func (m *AppConfiguration) GetWalletPreferences() []*WalletPreferences {
	if m != nil {
		return m.WalletPreferences
	}
	return nil
}

type CheckConnectionRequest struct {
	GrpcEndpoint         *GRPCEndpoint `protobuf:"bytes,1,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	RpcEndpoint          *RPCEndpoint  `protobuf:"bytes,2,opt,name=rpc_endpoint,json=rpcEndpoint,proto3" json:"rpc_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CheckConnectionRequest) Reset()         { *m = CheckConnectionRequest{} }
func (m *CheckConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*CheckConnectionRequest) ProtoMessage()    {}
func (*CheckConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{8}
}

func (m *CheckConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckConnectionRequest.Unmarshal(m, b)
}
func (m *CheckConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckConnectionRequest.Marshal(b, m, deterministic)
}
func (m *CheckConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckConnectionRequest.Merge(m, src)
}
func (m *CheckConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_CheckConnectionRequest.Size(m)
}
func (m *CheckConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckConnectionRequest proto.InternalMessageInfo

func (m *CheckConnectionRequest) GetGrpcEndpoint() *GRPCEndpoint {
	if m != nil {
		return m.GrpcEndpoint
	}
	return nil
}

func (m *CheckConnectionRequest) GetRpcEndpoint() *RPCEndpoint {
	if m != nil {
		return m.RpcEndpoint
	}
	return nil
}

type CheckConnectionResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckConnectionResponse) Reset()         { *m = CheckConnectionResponse{} }
func (m *CheckConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*CheckConnectionResponse) ProtoMessage()    {}
func (*CheckConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{9}
}

func (m *CheckConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckConnectionResponse.Unmarshal(m, b)
}
func (m *CheckConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckConnectionResponse.Marshal(b, m, deterministic)
}
func (m *CheckConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckConnectionResponse.Merge(m, src)
}
func (m *CheckConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_CheckConnectionResponse.Size(m)
}
func (m *CheckConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckConnectionResponse proto.InternalMessageInfo

func (m *CheckConnectionResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *CheckConnectionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ConnectWalletRequest struct {
	WalletEndpointId     string   `protobuf:"bytes,1,opt,name=wallet_endpoint_id,json=walletEndpointId,proto3" json:"wallet_endpoint_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectWalletRequest) Reset()         { *m = ConnectWalletRequest{} }
func (m *ConnectWalletRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectWalletRequest) ProtoMessage()    {}
func (*ConnectWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{10}
}

func (m *ConnectWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectWalletRequest.Unmarshal(m, b)
}
func (m *ConnectWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectWalletRequest.Marshal(b, m, deterministic)
}
func (m *ConnectWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectWalletRequest.Merge(m, src)
}
func (m *ConnectWalletRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectWalletRequest.Size(m)
}
func (m *ConnectWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectWalletRequest proto.InternalMessageInfo

func (m *ConnectWalletRequest) GetWalletEndpointId() string {
	if m != nil {
		return m.WalletEndpointId
	}
	return ""
}

type ConnectWalletResponse struct {
	IsSuccess            bool          `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	Error                string        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Endpoint             *GRPCEndpoint `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConnectWalletResponse) Reset()         { *m = ConnectWalletResponse{} }
func (m *ConnectWalletResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectWalletResponse) ProtoMessage()    {}
func (*ConnectWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{11}
}

func (m *ConnectWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectWalletResponse.Unmarshal(m, b)
}
func (m *ConnectWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectWalletResponse.Marshal(b, m, deterministic)
}
func (m *ConnectWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectWalletResponse.Merge(m, src)
}
func (m *ConnectWalletResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectWalletResponse.Size(m)
}
func (m *ConnectWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectWalletResponse proto.InternalMessageInfo

func (m *ConnectWalletResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *ConnectWalletResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ConnectWalletResponse) GetEndpoint() *GRPCEndpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

func init() {
	proto.RegisterEnum("dcrwalletgui.Network", Network_name, Network_value)
	proto.RegisterEnum("dcrwalletgui.SetConfigResponse_UpdateStatus", SetConfigResponse_UpdateStatus_name, SetConfigResponse_UpdateStatus_value)
	proto.RegisterType((*GetConfigRequest)(nil), "dcrwalletgui.GetConfigRequest")
	proto.RegisterType((*SetConfigRequest)(nil), "dcrwalletgui.SetConfigRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "dcrwalletgui.SetConfigResponse")
	proto.RegisterType((*RPCEndpoint)(nil), "dcrwalletgui.RPCEndpoint")
	proto.RegisterType((*GRPCEndpoint)(nil), "dcrwalletgui.GRPCEndpoint")
	proto.RegisterType((*AccountPreference)(nil), "dcrwalletgui.AccountPreference")
	proto.RegisterType((*WalletPreferences)(nil), "dcrwalletgui.WalletPreferences")
	proto.RegisterType((*AppConfiguration)(nil), "dcrwalletgui.AppConfiguration")
	proto.RegisterType((*CheckConnectionRequest)(nil), "dcrwalletgui.CheckConnectionRequest")
	proto.RegisterType((*CheckConnectionResponse)(nil), "dcrwalletgui.CheckConnectionResponse")
	proto.RegisterType((*ConnectWalletRequest)(nil), "dcrwalletgui.ConnectWalletRequest")
	proto.RegisterType((*ConnectWalletResponse)(nil), "dcrwalletgui.ConnectWalletResponse")
}

func init() { proto.RegisterFile("dcrwalletgui.proto", fileDescriptor_455734325031c3fa) }

var fileDescriptor_455734325031c3fa = []byte{
	// 886 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0xae, 0xb3, 0x3f, 0x89, 0x4f, 0x9c, 0xd4, 0x19, 0xb5, 0xd4, 0x04, 0x68, 0x57, 0x66, 0x91,
	0x56, 0x50, 0x6d, 0xa5, 0x80, 0xb8, 0xe1, 0x4f, 0x4b, 0x36, 0x94, 0x15, 0x6c, 0x5a, 0xc6, 0x59,
	0x95, 0x2b, 0x2c, 0xc7, 0x33, 0xd9, 0xb5, 0xea, 0x7a, 0xa6, 0x33, 0x36, 0x2b, 0xb8, 0xe5, 0x82,
	0x4b, 0x2e, 0x79, 0x83, 0x3e, 0x0c, 0x4f, 0xc0, 0x23, 0xf0, 0x18, 0xc8, 0x33, 0x8e, 0x63, 0x3b,
	0x69, 0xa3, 0x45, 0xdc, 0xe5, 0x7c, 0x73, 0xfe, 0xbe, 0x6f, 0x8e, 0xcf, 0x04, 0x10, 0x09, 0xc5,
	0x75, 0x10, 0xc7, 0x34, 0xbd, 0xcc, 0xa2, 0x63, 0x2e, 0x58, 0xca, 0x90, 0x55, 0xc5, 0xdc, 0x11,
	0xd8, 0x8f, 0x69, 0x3a, 0x66, 0xc9, 0x22, 0xba, 0xc4, 0xf4, 0x65, 0x46, 0x65, 0x8a, 0xee, 0x03,
	0xf0, 0x40, 0x4a, 0x7e, 0x25, 0x02, 0x49, 0x1d, 0xe3, 0xc0, 0x38, 0xb2, 0x70, 0x05, 0x71, 0x5f,
	0x82, 0xed, 0x35, 0x63, 0xbe, 0x00, 0x08, 0x38, 0xf7, 0x43, 0x05, 0xaa, 0x98, 0xee, 0xe8, 0xfe,
	0x71, 0xad, 0xfc, 0x09, 0xe7, 0x3a, 0x26, 0x13, 0x41, 0x1a, 0xb1, 0x04, 0x9b, 0xc1, 0x12, 0x69,
	0x94, 0x6c, 0xad, 0x95, 0xfc, 0xc7, 0x80, 0x41, 0xa5, 0xa6, 0xe4, 0x2c, 0x91, 0x14, 0xfd, 0x00,
	0xbd, 0x8c, 0x93, 0x20, 0xa5, 0xbe, 0x4c, 0x83, 0x34, 0x93, 0xaa, 0x6e, 0x7f, 0xf4, 0xb0, 0x5e,
	0x77, 0x2d, 0xee, 0xf8, 0x42, 0x05, 0x79, 0x2a, 0x06, 0x5b, 0x59, 0xc5, 0x42, 0xef, 0x01, 0x50,
	0x21, 0x98, 0xf0, 0x43, 0x46, 0x74, 0x23, 0x7b, 0xd8, 0x54, 0xc8, 0x98, 0x11, 0x8a, 0x3e, 0x82,
	0x81, 0x3e, 0x26, 0x54, 0x86, 0x22, 0xe2, 0x39, 0x0f, 0x67, 0xe7, 0xc0, 0x38, 0x32, 0xb1, 0xad,
	0x0e, 0x4e, 0x57, 0xb8, 0xfb, 0x09, 0x58, 0xd5, 0x4a, 0x08, 0x41, 0xdf, 0x9b, 0x9d, 0xcc, 0x2e,
	0x3c, 0xdf, 0xbb, 0x18, 0x8f, 0x27, 0x9e, 0x67, 0xdf, 0x42, 0x36, 0x58, 0x05, 0x36, 0xc1, 0xf8,
	0x09, 0xb6, 0x0d, 0xf7, 0x8f, 0x16, 0x74, 0xf1, 0xd3, 0xf1, 0x24, 0x21, 0x9c, 0x45, 0x49, 0x8a,
	0xfa, 0xd0, 0x8a, 0x88, 0x62, 0x66, 0xe2, 0x56, 0x44, 0xd0, 0x10, 0x3a, 0x57, 0x4c, 0xa6, 0x49,
	0xf0, 0x42, 0xf7, 0x67, 0xe2, 0xd2, 0x46, 0x08, 0x76, 0x39, 0x13, 0xa9, 0xea, 0xa8, 0x87, 0xd5,
	0xef, 0xdc, 0x3f, 0x93, 0x54, 0x28, 0xff, 0x5d, 0xed, 0xbf, 0xb4, 0xf3, 0xb3, 0x5c, 0xe4, 0x6b,
	0x26, 0x88, 0xb3, 0xa7, 0xcf, 0x96, 0x36, 0x3a, 0x84, 0x7e, 0x48, 0x45, 0xea, 0x2f, 0xa2, 0x98,
	0xfa, 0x2a, 0x7a, 0x5f, 0x79, 0x58, 0x39, 0xfa, 0x4d, 0x14, 0xd3, 0x69, 0x9e, 0xe1, 0x1d, 0x30,
	0x95, 0xd7, 0x3c, 0x66, 0x73, 0xa7, 0xad, 0x53, 0xe4, 0xc0, 0xd7, 0x31, 0x9b, 0xa3, 0x47, 0xd0,
	0x4e, 0x68, 0x7a, 0xcd, 0xc4, 0x73, 0xa7, 0xa3, 0x6e, 0xe6, 0x6e, 0xfd, 0x66, 0xa6, 0xfa, 0x10,
	0x2f, 0xbd, 0xd0, 0x1d, 0xd8, 0x8b, 0x83, 0x39, 0x8d, 0x1d, 0x53, 0x65, 0xd2, 0x86, 0xfb, 0xb7,
	0x01, 0xd6, 0xe3, 0xff, 0x53, 0x92, 0x75, 0x6a, 0xbb, 0xdb, 0xa8, 0xed, 0xbd, 0x9e, 0xda, 0xfe,
	0xcd, 0xa8, 0xb5, 0xab, 0xd4, 0x7e, 0x85, 0xc1, 0x49, 0x18, 0xb2, 0x2c, 0x49, 0x9f, 0x0a, 0xba,
	0xa0, 0x82, 0x26, 0x21, 0x45, 0x87, 0xd0, 0x0b, 0x34, 0x38, 0xcd, 0x5e, 0xcc, 0xa9, 0x50, 0x4c,
	0x7b, 0xb8, 0x0e, 0xe6, 0xed, 0x45, 0xd2, 0xbf, 0x8a, 0x08, 0xa1, 0x89, 0x62, 0xdd, 0xc1, 0x9d,
	0x48, 0x7e, 0xab, 0x6c, 0xe4, 0x82, 0x45, 0x22, 0xc9, 0xe3, 0xe0, 0x97, 0x27, 0x82, 0x50, 0x51,
	0xb0, 0xaf, 0x61, 0xee, 0xef, 0x06, 0x0c, 0x9e, 0xa9, 0x86, 0x57, 0xb5, 0x25, 0x7a, 0x08, 0x48,
	0xb3, 0xf0, 0x69, 0x21, 0xb7, 0x5f, 0x6a, 0x6d, 0xeb, 0x93, 0xe5, 0x3d, 0x9c, 0x11, 0x74, 0x5a,
	0xb6, 0xea, 0x73, 0x41, 0x17, 0xd2, 0x69, 0x1d, 0xec, 0x1c, 0x75, 0x47, 0x0f, 0x1a, 0x5f, 0x7e,
	0x93, 0x22, 0xb6, 0x82, 0x15, 0x24, 0xdd, 0x57, 0x2d, 0xb0, 0x9b, 0xdb, 0x01, 0x7d, 0x09, 0x3d,
	0x12, 0x0a, 0x52, 0xb6, 0x51, 0x2c, 0x95, 0xb7, 0xeb, 0xa9, 0x2b, 0x63, 0x81, 0xf3, 0xcd, 0x46,
	0xca, 0x21, 0x99, 0x80, 0xdd, 0x20, 0xb2, 0xec, 0x6e, 0x58, 0x4f, 0x51, 0x1d, 0x2d, 0x7c, 0xbb,
	0x4e, 0x51, 0xa2, 0xcf, 0x60, 0x48, 0xe8, 0x22, 0xc8, 0xe2, 0xd4, 0xdf, 0xa0, 0x8b, 0xfe, 0xf4,
	0xef, 0x15, 0x1e, 0xcf, 0x9a, 0xf2, 0x4c, 0x4b, 0x31, 0xf9, 0x4a, 0x62, 0x67, 0x77, 0x93, 0x46,
	0x6b, 0x37, 0x81, 0x07, 0xd7, 0x4d, 0xc8, 0xfd, 0xd3, 0x80, 0xb7, 0xc6, 0x57, 0x34, 0x7c, 0x3e,
	0x66, 0x49, 0x42, 0x43, 0xb5, 0x45, 0x8b, 0x05, 0xfc, 0x15, 0xf4, 0x2e, 0x05, 0x0f, 0x9b, 0x72,
	0xbd, 0x89, 0xab, 0x95, 0x07, 0x94, 0x7a, 0x7d, 0x0e, 0x56, 0x2d, 0xbe, 0xb5, 0x4d, 0xee, 0x6e,
	0x25, 0xda, 0x3d, 0x87, 0x7b, 0x6b, 0x8d, 0x15, 0x5b, 0xfa, 0xdd, 0x7c, 0x50, 0xbd, 0x2c, 0x0c,
	0xa9, 0xd4, 0x1b, 0xba, 0x83, 0x57, 0x40, 0xfe, 0x5d, 0xa8, 0xc5, 0x59, 0x7c, 0xb8, 0xda, 0x70,
	0x4f, 0xe1, 0x4e, 0x91, 0x49, 0xeb, 0xb2, 0x64, 0x79, 0xa3, 0xe9, 0x74, 0x7f, 0x33, 0xe0, 0x6e,
	0x23, 0xcd, 0x7f, 0xef, 0x09, 0x7d, 0x0a, 0x9d, 0x52, 0x9c, 0x9d, 0xad, 0xe2, 0x96, 0xbe, 0x1f,
	0x3e, 0x82, 0x76, 0xb1, 0x0d, 0x50, 0x17, 0xda, 0xe7, 0x27, 0x67, 0xd3, 0xe9, 0x64, 0x66, 0xdf,
	0xca, 0x8d, 0xd9, 0xc4, 0x9b, 0xe5, 0x86, 0x81, 0x00, 0xf6, 0xbd, 0xb3, 0xf3, 0xfc, 0x77, 0x6b,
	0xf4, 0xca, 0x00, 0xb3, 0xfc, 0x1c, 0xd0, 0x77, 0x60, 0x96, 0x2f, 0x34, 0x6a, 0x3c, 0xa9, 0xcd,
	0xa7, 0x7b, 0xb8, 0xe5, 0xc9, 0x45, 0xdf, 0x83, 0xe9, 0xbd, 0x2e, 0x59, 0xf3, 0x4d, 0x1f, 0x3e,
	0xd8, 0xf2, 0x8e, 0x8e, 0xfe, 0x32, 0xa0, 0x5f, 0x50, 0xf3, 0xa8, 0xf8, 0x39, 0x0a, 0x29, 0xfa,
	0x09, 0x6e, 0x37, 0xe6, 0x00, 0x1d, 0xd6, 0xd3, 0x6c, 0x9e, 0xdf, 0xe1, 0x07, 0x5b, 0xbc, 0x8a,
	0x8b, 0xfb, 0x11, 0x7a, 0xb5, 0x1b, 0x45, 0x6e, 0x23, 0x6e, 0xc3, 0xd4, 0x0c, 0xdf, 0x7f, 0xa3,
	0x8f, 0xce, 0x3c, 0xdf, 0x57, 0x7f, 0x8f, 0x3e, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x58, 0x2c,
	0xc4, 0x4d, 0x34, 0x09, 0x00, 0x00,
}
