// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dcrwalletgui.proto

package dcrwalletgui

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetConfigResponse_UpdateStatus int32

const (
	SetConfigResponse_STATUS_SUCCESS SetConfigResponse_UpdateStatus = 0
	SetConfigResponse_STATUS_ERROR   SetConfigResponse_UpdateStatus = 1
)

var SetConfigResponse_UpdateStatus_name = map[int32]string{
	0: "STATUS_SUCCESS",
	1: "STATUS_ERROR",
}

var SetConfigResponse_UpdateStatus_value = map[string]int32{
	"STATUS_SUCCESS": 0,
	"STATUS_ERROR":   1,
}

func (x SetConfigResponse_UpdateStatus) String() string {
	return proto.EnumName(SetConfigResponse_UpdateStatus_name, int32(x))
}

func (SetConfigResponse_UpdateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{2, 0}
}

type AppConfiguration_Network int32

const (
	AppConfiguration_MAINNET AppConfiguration_Network = 0
	AppConfiguration_TESTNET AppConfiguration_Network = 1
	AppConfiguration_SIMNET  AppConfiguration_Network = 2
)

var AppConfiguration_Network_name = map[int32]string{
	0: "MAINNET",
	1: "TESTNET",
	2: "SIMNET",
}

var AppConfiguration_Network_value = map[string]int32{
	"MAINNET": 0,
	"TESTNET": 1,
	"SIMNET":  2,
}

func (x AppConfiguration_Network) String() string {
	return proto.EnumName(AppConfiguration_Network_name, int32(x))
}

func (AppConfiguration_Network) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{3, 0}
}

type GetConfigRequest struct {
	Passphrase           []byte   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{0}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

type SetConfigRequest struct {
	AppConfig            *AppConfiguration `protobuf:"bytes,1,opt,name=app_config,json=appConfig,proto3" json:"app_config,omitempty"`
	Passphrase           []byte            `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{1}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetAppConfig() *AppConfiguration {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

func (m *SetConfigRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

type SetConfigResponse struct {
	UpdateStatus         SetConfigResponse_UpdateStatus `protobuf:"varint,1,opt,name=update_status,json=updateStatus,proto3,enum=dcrwalletgui.SetConfigResponse_UpdateStatus" json:"update_status,omitempty"`
	ErrorCode            int32                          `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorDescription     string                         `protobuf:"bytes,3,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SetConfigResponse) Reset()         { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()    {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{2}
}

func (m *SetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigResponse.Unmarshal(m, b)
}
func (m *SetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigResponse.Merge(m, src)
}
func (m *SetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigResponse.Size(m)
}
func (m *SetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigResponse proto.InternalMessageInfo

func (m *SetConfigResponse) GetUpdateStatus() SetConfigResponse_UpdateStatus {
	if m != nil {
		return m.UpdateStatus
	}
	return SetConfigResponse_STATUS_SUCCESS
}

func (m *SetConfigResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *SetConfigResponse) GetErrorDescription() string {
	if m != nil {
		return m.ErrorDescription
	}
	return ""
}

type AppConfiguration struct {
	DcrdHost             *AppConfiguration_RPCEndpoint   `protobuf:"bytes,1,opt,name=dcrd_host,json=dcrdHost,proto3" json:"dcrd_host,omitempty"`
	DcrwalletHosts       []*AppConfiguration_RPCEndpoint `protobuf:"bytes,2,rep,name=dcrwallet_hosts,json=dcrwalletHosts,proto3" json:"dcrwallet_hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *AppConfiguration) Reset()         { *m = AppConfiguration{} }
func (m *AppConfiguration) String() string { return proto.CompactTextString(m) }
func (*AppConfiguration) ProtoMessage()    {}
func (*AppConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{3}
}

func (m *AppConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfiguration.Unmarshal(m, b)
}
func (m *AppConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfiguration.Marshal(b, m, deterministic)
}
func (m *AppConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfiguration.Merge(m, src)
}
func (m *AppConfiguration) XXX_Size() int {
	return xxx_messageInfo_AppConfiguration.Size(m)
}
func (m *AppConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfiguration proto.InternalMessageInfo

func (m *AppConfiguration) GetDcrdHost() *AppConfiguration_RPCEndpoint {
	if m != nil {
		return m.DcrdHost
	}
	return nil
}

func (m *AppConfiguration) GetDcrwalletHosts() []*AppConfiguration_RPCEndpoint {
	if m != nil {
		return m.DcrwalletHosts
	}
	return nil
}

type AppConfiguration_RPCEndpoint struct {
	Hostname             string                   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 uint32                   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username             string                   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string                   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CertFileName         string                   `protobuf:"bytes,5,opt,name=cert_file_name,json=certFileName,proto3" json:"cert_file_name,omitempty"`
	CertBlob             string                   `protobuf:"bytes,6,opt,name=cert_blob,json=certBlob,proto3" json:"cert_blob,omitempty"`
	Network              AppConfiguration_Network `protobuf:"varint,7,opt,name=network,proto3,enum=dcrwalletgui.AppConfiguration_Network" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AppConfiguration_RPCEndpoint) Reset()         { *m = AppConfiguration_RPCEndpoint{} }
func (m *AppConfiguration_RPCEndpoint) String() string { return proto.CompactTextString(m) }
func (*AppConfiguration_RPCEndpoint) ProtoMessage()    {}
func (*AppConfiguration_RPCEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_455734325031c3fa, []int{3, 0}
}

func (m *AppConfiguration_RPCEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfiguration_RPCEndpoint.Unmarshal(m, b)
}
func (m *AppConfiguration_RPCEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfiguration_RPCEndpoint.Marshal(b, m, deterministic)
}
func (m *AppConfiguration_RPCEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfiguration_RPCEndpoint.Merge(m, src)
}
func (m *AppConfiguration_RPCEndpoint) XXX_Size() int {
	return xxx_messageInfo_AppConfiguration_RPCEndpoint.Size(m)
}
func (m *AppConfiguration_RPCEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfiguration_RPCEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfiguration_RPCEndpoint proto.InternalMessageInfo

func (m *AppConfiguration_RPCEndpoint) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *AppConfiguration_RPCEndpoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *AppConfiguration_RPCEndpoint) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AppConfiguration_RPCEndpoint) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AppConfiguration_RPCEndpoint) GetCertFileName() string {
	if m != nil {
		return m.CertFileName
	}
	return ""
}

func (m *AppConfiguration_RPCEndpoint) GetCertBlob() string {
	if m != nil {
		return m.CertBlob
	}
	return ""
}

func (m *AppConfiguration_RPCEndpoint) GetNetwork() AppConfiguration_Network {
	if m != nil {
		return m.Network
	}
	return AppConfiguration_MAINNET
}

func init() {
	proto.RegisterEnum("dcrwalletgui.SetConfigResponse_UpdateStatus", SetConfigResponse_UpdateStatus_name, SetConfigResponse_UpdateStatus_value)
	proto.RegisterEnum("dcrwalletgui.AppConfiguration_Network", AppConfiguration_Network_name, AppConfiguration_Network_value)
	proto.RegisterType((*GetConfigRequest)(nil), "dcrwalletgui.GetConfigRequest")
	proto.RegisterType((*SetConfigRequest)(nil), "dcrwalletgui.SetConfigRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "dcrwalletgui.SetConfigResponse")
	proto.RegisterType((*AppConfiguration)(nil), "dcrwalletgui.AppConfiguration")
	proto.RegisterType((*AppConfiguration_RPCEndpoint)(nil), "dcrwalletgui.AppConfiguration.RPCEndpoint")
}

func init() { proto.RegisterFile("dcrwalletgui.proto", fileDescriptor_455734325031c3fa) }

var fileDescriptor_455734325031c3fa = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xfb, 0x91, 0xd4, 0x13, 0x37, 0xb8, 0x73, 0xb2, 0x82, 0x28, 0x51, 0x84, 0x50, 0x05,
	0x28, 0x48, 0x81, 0x2b, 0x12, 0x21, 0x84, 0x52, 0x41, 0x03, 0xec, 0x26, 0x67, 0xcb, 0xb1, 0xb7,
	0xad, 0x85, 0xf1, 0x6e, 0x77, 0xd7, 0xca, 0x3f, 0xe2, 0x67, 0x71, 0xe6, 0x37, 0x70, 0x42, 0xbb,
	0x4e, 0x8c, 0xeb, 0x0a, 0x22, 0x6e, 0x3b, 0x6f, 0xe6, 0xbd, 0x97, 0x8c, 0xe6, 0x19, 0x30, 0x89,
	0xe5, 0x2a, 0xca, 0x32, 0xa6, 0xaf, 0x8a, 0x74, 0x28, 0x24, 0xd7, 0x1c, 0xbd, 0x3a, 0x36, 0x18,
	0x81, 0x7f, 0xc6, 0xf4, 0x84, 0xe7, 0x97, 0xe9, 0x15, 0x61, 0x37, 0x05, 0x53, 0x1a, 0x4f, 0x00,
	0x44, 0xa4, 0x94, 0xb8, 0x96, 0x91, 0x62, 0x81, 0xd3, 0x77, 0x4e, 0x3d, 0x52, 0x43, 0x06, 0x37,
	0xe0, 0xd3, 0x26, 0xe7, 0x15, 0x40, 0x24, 0x44, 0x18, 0x5b, 0xd0, 0x72, 0x3a, 0xa3, 0x93, 0xe1,
	0x2d, 0xfb, 0xb1, 0x10, 0x25, 0xa7, 0x90, 0x91, 0x4e, 0x79, 0x4e, 0xdc, 0x68, 0x83, 0x34, 0x2c,
	0x77, 0xef, 0x58, 0xfe, 0x74, 0xe0, 0xb8, 0xe6, 0xa9, 0x04, 0xcf, 0x15, 0xc3, 0x2f, 0x70, 0x54,
	0x88, 0x24, 0xd2, 0x2c, 0x54, 0x3a, 0xd2, 0x85, 0xb2, 0xbe, 0xdd, 0xd1, 0xb3, 0xdb, 0xbe, 0x77,
	0x78, 0xc3, 0x85, 0x25, 0x51, 0xcb, 0x21, 0x5e, 0x51, 0xab, 0xf0, 0x01, 0x00, 0x93, 0x92, 0xcb,
	0x30, 0xe6, 0x49, 0xf9, 0x43, 0x0e, 0x88, 0x6b, 0x91, 0x09, 0x4f, 0x18, 0x3e, 0x85, 0xe3, 0xb2,
	0x9d, 0x30, 0x15, 0xcb, 0x54, 0x98, 0xff, 0x11, 0xec, 0xf5, 0x9d, 0x53, 0x97, 0xf8, 0xb6, 0xf1,
	0xf6, 0x0f, 0x3e, 0x78, 0x09, 0x5e, 0xdd, 0x09, 0x11, 0xba, 0x74, 0x3e, 0x9e, 0x2f, 0x68, 0x48,
	0x17, 0x93, 0xc9, 0x94, 0x52, 0x7f, 0x07, 0x7d, 0xf0, 0xd6, 0xd8, 0x94, 0x90, 0x4f, 0xc4, 0x77,
	0x06, 0x3f, 0xf6, 0xc0, 0x6f, 0xae, 0x0a, 0xcf, 0xc0, 0x4d, 0x62, 0x99, 0x84, 0xd7, 0x5c, 0xe9,
	0xf5, 0x76, 0x9f, 0xfc, 0x7b, 0xbb, 0x43, 0xf2, 0x79, 0x32, 0xcd, 0x13, 0xc1, 0xd3, 0x5c, 0x93,
	0x43, 0x43, 0x7e, 0xcf, 0x95, 0x46, 0x0a, 0xf7, 0x2a, 0x9a, 0x55, 0x53, 0xc1, 0x6e, 0x7f, 0xef,
	0x3f, 0xe5, 0xba, 0xd5, 0xa8, 0xd1, 0x54, 0xbd, 0x5f, 0x0e, 0x74, 0x6a, 0x7d, 0xec, 0xc1, 0xa1,
	0x91, 0xce, 0xa3, 0x6f, 0xe5, 0xf9, 0xb8, 0xa4, 0xaa, 0x11, 0x61, 0x5f, 0x70, 0xa9, 0xed, 0x6a,
	0x8f, 0x88, 0x7d, 0x9b, 0xf9, 0x42, 0x31, 0x69, 0xe7, 0xcb, 0x65, 0x56, 0xb5, 0xe9, 0x99, 0x3b,
	0x58, 0x71, 0x99, 0x04, 0xfb, 0x65, 0x6f, 0x53, 0xe3, 0x23, 0xe8, 0xc6, 0x4c, 0xea, 0xf0, 0x32,
	0xcd, 0x58, 0x68, 0xd9, 0x07, 0x76, 0xc2, 0x33, 0xe8, 0xbb, 0x34, 0x63, 0x33, 0xa3, 0x70, 0x1f,
	0x5c, 0x3b, 0xb5, 0xcc, 0xf8, 0x32, 0x68, 0x95, 0x12, 0x06, 0x78, 0x93, 0xf1, 0x25, 0xbe, 0x86,
	0x76, 0xce, 0xf4, 0x8a, 0xcb, 0xaf, 0x41, 0xdb, 0x1e, 0xcf, 0xe3, 0x2d, 0x7b, 0x98, 0x95, 0xd3,
	0x64, 0x43, 0x1b, 0x3c, 0x87, 0xf6, 0x1a, 0xc3, 0x0e, 0xb4, 0x2f, 0xc6, 0xe7, 0xb3, 0xd9, 0x74,
	0xee, 0xef, 0x98, 0x62, 0x3e, 0xa5, 0x73, 0x53, 0x38, 0x08, 0xd0, 0xa2, 0xe7, 0x17, 0xe6, 0xbd,
	0x3b, 0xfa, 0xee, 0x80, 0x5b, 0xc9, 0xe2, 0x07, 0x70, 0xab, 0x00, 0x62, 0x23, 0x31, 0xcd, 0x64,
	0xf6, 0xb6, 0x24, 0x0a, 0x3f, 0x82, 0x4b, 0xff, 0x26, 0xd6, 0x8c, 0x6c, 0xef, 0xe1, 0x96, 0x98,
	0x2c, 0x5b, 0xf6, 0x83, 0xf1, 0xe2, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x56, 0x19, 0xb6,
	0x46, 0x04, 0x00, 0x00,
}
