name: Go build

on:
  pull_request:
    paths:
        - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14']
    defaults:
      run:
        shell: bash
        working-directory: app

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
          go-version: ${{ matrix.go }}

    - name: install deps
      run: sudo apt-get update && sudo apt-get install -y -q --no-install-recommends libwebkit2gtk-4.0-dev libgtk-3-dev libcairo2-dev libglib2.0-dev libappindicator3-dev libappindicator3-0.1-cil-dev

    - name: build
      run: go build -v

