name: linux_build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    strategy:
      matrix:
        go: [ '1.17']
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install -g yarn

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
          go-version: ${{ matrix.go }}

    - name: install deps
      run: sudo apt-get update && sudo apt-get install -y -q --no-install-recommends libwebkit2gtk-4.0-dev libgtk-3-dev libglib2.0-dev libappindicator3-dev libayatana-appindicator3-dev

    - name: Build
      run: |
        go install github.com/markbates/pkger/cmd/pkger@v0.17.1
        ./build-linux.sh

